In [1]:
library(tidyverse)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.6     ✔ purrr   0.3.4
✔ tibble  3.1.7     ✔ dplyr   1.0.7
✔ tidyr   1.1.4     ✔ stringr 1.4.0
✔ readr   2.0.2     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [2]:
ace_total <- read.table("/u/home/a/afcarrol/project-pasaniuc/Projects/20240109_subset_ACE_AFR_for_SAIGE/ace_list.txt")

In [4]:
head(ace_total)

  V1
1 AU003305_AU003305
2 AU0226302_AU0226302
3 AU0226303_AU0226303
4 AU025304_AU025304
5 AU025804_AU025804
6 MN.308_MN.308

In [5]:
colnames(ace_total) <- c("IID")

In [12]:
dim(ace_total)

[1] 2612    1

In [6]:
ace_covar <- read.csv("/u/home/a/afcarrol/project-pasaniuc/Projects/20240109_subset_ACE_AFR_for_SAIGE/ace_covar.csv")

In [7]:
head(ace_covar)

  vcf.ID                        IID            FID         SEX dx age PC1
1 702-A-80310.01_702-A-80310.01 702-A-80310.01 702-A-80310 1   NA NA  -59.20396
2 702-A-80310.02_702-A-80310.02 702-A-80310.02 702-A-80310 2   NA NA  -70.83652
3 702-A-80310.03_702-A-80310.03 702-A-80310.03 702-A-80310 1   NA NA  -65.44799
4 702-A-80310.04_702-A-80310.04 702-A-80310.04 702-A-80310 1   NA NA  -66.49899
5 702-A-80310.05_702-A-80310.05 702-A-80310.05 702-A-80310 2   NA NA  -64.56624
6 702-A-80330.01_702-A-80330.01 702-A-80330.01 702-A-80330 1   NA NA  -69.06192
  PC2       PC3       PC4      ... PC13        PC14        PC15     PC16
1 21.898834 -74.07577 63.78452 ... -6.49634460 -0.06024645 7.237338 -52.26812
2 64.028260 -53.23033 11.79616 ...  1.29570805  0.46195499 1.806164 -28.97094
3 39.064043 -65.51733 41.20630 ... -3.72554381  1.32306199 4.095155 -44.62658
4 46.010683 -63.47658 35.34593 ... -0.01174978  2.31100273 7.981447 -44.73312
5 37.548055 -71.61951 46.30474 ... -2.03119072  1.00376214 4.425171 -43.74187
6  4.943752 -97.16606 76.97857 ... -7.97318990 -2.45305754 5.905170 -57.25083
  PC17      PC18       PC19       PC20       data ancestry
1 -14.34788 -13.893078  0.5879248 10.1966165 ace  AMR
2 -13.70503   4.355163 -1.6504476 -0.2859964 ace  AMR
3 -14.73959  -1.790906  0.8654015 10.9098518 ace  AMR
4 -13.00900  -9.808721 -4.8037655  5.1445242 ace  AMR
5 -19.23304  -3.839576  0.4724755  5.1736369 ace  AMR
6 -23.27042   5.275870  2.8850064 -1.4868289 ace  AMR

In [8]:
dim(ace_total)

[1] 2612    1

In [14]:
ace_afr <- ace_total[ace_total$IID %in% ace_covar[ace_covar$ancestry == "AFR",]$vcf.ID,]

In [16]:
head(ace_afr)

[1] "AU2107302_AU2107302" "AU2107303_AU2107303" "AU2103302_AU2103302"
[4] "AU2103301_AU2103301" "AU1983303_AU1983303" "AU2403305_AU2403305"

In [15]:
length(ace_afr)

[1] 1146

In [17]:
sample_list_file <- "ace_afr_list.txt"

# Write the column to a text file
writeLines(as.character(ace_afr), sample_list_file)