In [1]:
library(dplyr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [1]:
library(IRkernel)

In [4]:
IRkernel::installspec(user = FALSE)# nothing?

In [2]:
getwd()

[1] "/u/project/pasaniuc/afcarrol/Projects/20230930_1kg_variants"

In [3]:
one_kg <- read.table('/u/project/pasaniuc/afcarrol/Projects/20230930_1kg_variants/1kg_var.snplist')

In [4]:
head(one_kg)

  V1
1 1:58814:G:A
2 1:792461:G:A
3 1:817341:A:G
4 1:823656:G:A
5 1:858952:G:A
6 1:894801:A:G

In [7]:
one_kg$id <- paste("chr", one_kg$V1, sep = "")

In [8]:
head(one_kg)

  V1           id
1 1:58814:G:A  chr1:58814:G:A
2 1:792461:G:A chr1:792461:G:A
3 1:817341:A:G chr1:817341:A:G
4 1:823656:G:A chr1:823656:G:A
5 1:858952:G:A chr1:858952:G:A
6 1:894801:A:G chr1:894801:A:G

In [ ]:
# Split the entries by colon and store the result in a new data frame
one_kg <- as.data.frame(do.call(rbind, strsplit(one_kg$V1, ":")))

# Rename the columns
colnames(one_kg) <- c("chrom", "pos", "ref", "alt")

In [5]:
imputed_data <- read.table('/u/project/geschwind/shared/GenomicDatasets-processed/Imputed/total_vcfs_r2_0.8/combined/merged_output_2_var.txt')

In [6]:
head(imputed_data)

  V1    V2    V3                V4  V5
1 chr10 12040 chr10:12040:G:A   G   A
2 chr10 14470 chr10:14470:C:T   C   T
3 chr10 31093 chr10:31093:GAC:G GAC G
4 chr10 36953 chr10:36953:G:C   G   C
5 chr10 37005 chr10:37005:C:A   C   A
6 chr10 40467 chr10:40467:A:C   A   C

In [9]:
final_snps <- imputed_data[imputed_data$V3 %in% one_kg$id ,]

In [10]:
dim(one_kg)

[1] 443129      2

In [11]:
dim(final_snps)

[1] 426243      5

In [12]:
table(table(final_snps$V3))

     1
426243

In [5]:
head(final_snps)

ERROR: Error in head(final_snps): object 'final_snps' not found

In [13]:
write.csv(final_snps, file = "filtered_ace_1kg_snps.csv", row.names = FALSE)

In [ ]:
final_snps <- read.csv("filtered_snps.csv")

In [14]:
writeLines(as.character(final_snps$V3), con = "filtered_snps_1kg_ace.txt")