In [1]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [4]:
ace_covar <- read.table("ACE_covariate_file_re.txt", header = T)

In [5]:
head(ace_covar)

  IID       ASD Age   Sex PC1      PC2        PC3       PC4          PC5
1 AU2107302 1   15.50 1   126.7813  17.207581 -6.099833  -7.93894189  3.3557448
2 AU2107303 0   15.84 2   116.3248  24.253750 -7.431571 -11.76504677  3.3914912
3 AU2103302 0    7.53 1   194.1439  -9.919419 -2.228807   0.58988265 -0.9961817
4 AU2103301 1    7.53 1   195.1074 -11.289656 -3.532087   0.01506597 -2.0433400
5 AU1983303 1    7.72 1   135.0053  18.017600 -7.413121  -9.06346905 -1.1114506
6 AU2403305 1    4.34 2   196.3868 -10.328321 -1.793127   0.70936485 -3.2515919
  PC6        PC7        PC8       PC9        PC10
1  0.4170315  -4.597033  5.871356  2.8834624 -5.220948
2  1.2858980  -3.307193  3.644136  0.5097405 -2.037802
3  0.4446859  -6.545726 26.352618  3.5809226  2.796863
4  0.5284942 -10.040292 28.215147  3.7739942  4.553534
5  1.6653925  -3.811969 12.464832  0.2991903 -3.739108
6 -0.4317270  27.121370 -2.871278 -2.8148308 -6.739495

In [6]:
ace_cc <- ace_covar[ace_covar$ASD %in% c(0,1),]

In [7]:
dim(ace_cc)

[1] 1092   14

In [8]:
table(table(ace_cc$IID))

   1
1092

In [23]:
table(ace_cc$ASD)

  0   1
618 474

In [11]:
spark_covar <- read.table("covar_file_saige.txt", header = T)

In [12]:
head(spark_covar)

  FID       IID       Age Sex ASD PC1       PC2        PC3        PC4
1 SF0000914 SP0025844 497 1   0   162.90333  0.5126609 -5.6791765  -1.724073
2 SF0001583 SP0001536 398 2   0   159.53368 -0.4437008 -5.2597911  -3.767932
3 SF0001583 SP0001583  60 1   1   129.97302 13.5162719 -9.4129636  -6.202651
4 SF0001583 SP0001720 453 1   0   113.52600 22.4859639 -8.6766201  -8.905824
5 SF0003386 SP0003386  54 1   1    70.20508 33.6585374 -0.8303692 -15.129232
6 SF0003386 SP0003414  23 1   1    72.62620 33.4963693 -2.7121802 -12.474572
  PC5       PC6        PC7         PC8        PC9         PC10
1 -4.009686  0.6606196  -9.2171288   8.101596  0.04062518  2.3290313
2 -2.489947  0.1155772  -4.6226349   7.186049  1.30890580 -0.2917196
3 -3.396206 -0.3216511  -0.8951926   4.417643 -1.75147069 -2.8047637
4 -2.270763  1.4299533  -3.3414043   7.579669 -1.61016047 -5.3114287
5 29.138770 -4.7567959 -21.8981683 -41.379100 -0.59442922  6.5259796
6 25.716398 -5.3438820 -19.6948795 -39.432922  0.76713408  3.2403588

In [13]:
spark_cc <- spark_covar[spark_covar$ASD %in% c(0,1),]

In [14]:
dim(spark_cc)

[1] 3764   15

In [15]:
table(table(spark_cc$IID))

   1
3764

In [16]:
table(spark_cc$ASD)

   0    1
1833 1931

In [18]:
spark_indv <- as.data.frame(spark_cc$IID)

In [19]:
ace_indv <- as.data.frame(ace_cc$IID)

In [20]:
dim(ace_indv)

[1] 1092    1

In [21]:
write.csv(spark_indv, "spark_saige_indv.csv")

In [22]:
write.csv(ace_indv, "ace_saige_indv.csv")