In [1]:
library(tidyverse)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.6     ✔ purrr   0.3.4
✔ tibble  3.1.7     ✔ dplyr   1.0.7
✔ tidyr   1.1.4     ✔ stringr 1.4.0
✔ readr   2.0.2     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [4]:
# Set the directory path containing the files
directory_path <- "/u/home/a/afcarrol/project-pasaniuc/Projects/20240229_ace_partial_pgs/out/"
# Initialize an empty data frame to store the results
result <- data.frame()

In [13]:

# Loop through files from ace_chr1 to ace_chr22
for (chr in 1:22) {
    
#    chr <- 1
  # Construct the file path
  file_path <- paste0(directory_path, "ace_chr", chr, ".sample_pgs.tsv")
  print(file_path)
  # Read the data from the current file
  data <- read.table(file_path, header = TRUE, , sep = "\t")
  
  # Combine the results for each ancestry (ANC1 and ANC2)
  result <- rbind(result, data)
}

[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240229_ace_partial_pgs/out/ace_chr1.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240229_ace_partial_pgs/out/ace_chr2.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240229_ace_partial_pgs/out/ace_chr3.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240229_ace_partial_pgs/out/ace_chr4.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240229_ace_partial_pgs/out/ace_chr5.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240229_ace_partial_pgs/out/ace_chr6.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240229_ace_partial_pgs/out/ace_chr7.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240229_ace_partial_pgs/out/ace_chr8.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240229_ace_partial_pgs/out/ace_chr9.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240229_ace_partial_pgs/out/ace_chr10.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240229_ace_partial_pgs/out/ace_chr11.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240229_ace_partial_pgs/out/ace_chr12.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240229_ace_partial_pgs/out/ace_chr13.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240229_ace_partial_pgs/out/ace_chr14.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240229_ace_partial_pgs/out/ace_chr15.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240229_ace_partial_pgs/out/ace_chr16.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240229_ace_partial_pgs/out/ace_chr17.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240229_ace_partial_pgs/out/ace_chr18.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240229_ace_partial_pgs/out/ace_chr19.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240229_ace_partial_pgs/out/ace_chr20.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240229_ace_partial_pgs/out/ace_chr21.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240229_ace_partial_pgs/out/ace_chr22.sample_pgs.tsv"

In [15]:
result[result$indiv == "AU003305_AU003305",]

      indiv             ANC1       ANC2
1     AU003305_AU003305         NA -0.0329995
2613  AU003305_AU003305         NA  0.0000000
5225  AU003305_AU003305         NA  0.0000000
7837  AU003305_AU003305         NA  0.0000000
10449 AU003305_AU003305         NA -0.0406033
13061 AU003305_AU003305         NA  0.0000000
15673 AU003305_AU003305         NA -0.0030011
18285 AU003305_AU003305         NA  0.0000000
20897 AU003305_AU003305         NA  0.0000000
23509 AU003305_AU003305         NA         NA
26121 AU003305_AU003305         NA  0.0000000
28733 AU003305_AU003305         NA -0.1076935
31345 AU003305_AU003305 -0.9575417  0.0262037
33957 AU003305_AU003305         NA  0.0000000
36569 AU003305_AU003305         NA  0.0000000
39181 AU003305_AU003305         NA  0.0000000
41793 AU003305_AU003305         NA  0.0000000
44405 AU003305_AU003305  0.6567510  0.0000000
47017 AU003305_AU003305         NA  0.0000000
49629 AU003305_AU003305         NA  0.0000000
52241 AU003305_AU003305  0.1125060  0.0000000
54853 AU003305_AU003305 -0.1083206  0.0000000

In [21]:
# Sum the scores across all chromosomes for each individual by ancestry
final_result <- result %>%
  group_by(indiv) %>%
  summarize(
    ANC1_sum = sum(ANC1, na.rm = TRUE),
    ANC2_sum = sum(ANC2, na.rm = TRUE)
  )

In [22]:
final_result[final_result$indiv == "AU003305_AU003305",]

  indiv             ANC1_sum   ANC2_sum
1 AU003305_AU003305 -0.2966053 -0.1580937

In [23]:
0.6567510+0.1125060-0.9575417-0.1083206

[1] -0.2966053

In [24]:
head(final_result)

  indiv                         ANC1_sum  ANC2_sum
1 702-A-80310.01_702-A-80310.01 2.7715487  0.0269626
2 702-A-80310.02_702-A-80310.02 0.6065891 -0.2184343
3 702-A-80310.03_702-A-80310.03 2.2478616  0.1293762
4 702-A-80310.04_702-A-80310.04 0.0109115  0.4246643
5 702-A-80310.05_702-A-80310.05 1.6108252  0.0056481
6 702-A-80330.01_702-A-80330.01 0.0793134 -0.8087766

In [25]:
table(table(final_result$indiv))

   1
2612

In [26]:
final_result$total_pgs <- final_result$ANC1_sum+final_result$ANC2_sum

In [27]:
head(final_result)

  indiv                         ANC1_sum  ANC2_sum   total_pgs
1 702-A-80310.01_702-A-80310.01 2.7715487  0.0269626  2.7985113
2 702-A-80310.02_702-A-80310.02 0.6065891 -0.2184343  0.3881548
3 702-A-80310.03_702-A-80310.03 2.2478616  0.1293762  2.3772378
4 702-A-80310.04_702-A-80310.04 0.0109115  0.4246643  0.4355758
5 702-A-80310.05_702-A-80310.05 1.6108252  0.0056481  1.6164733
6 702-A-80330.01_702-A-80330.01 0.0793134 -0.8087766 -0.7294632

In [28]:
write_csv(final_result, "ace_anc_part_pgs.csv")