In [1]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [13]:
msp_ace_3_path <-  "/u/project/pasaniuc/aflynnca/projects/20240423_ace_partial_hm3/rfmix_out/chr3.msp.tsv"
col_names <- readLines(msp_ace_3_path, n = 2)[2]
col_names <- strsplit(col_names, "\t")[[1]]
col_names[1] <- substring(col_names[1], 2)

In [14]:
msp_ace_3 <- read.table(msp_ace_3_path, header = FALSE, sep = "\t", col.names = col_names)

In [ ]:
#"snp"	"CHROM"	"POS"	"REF"	"ALT"	"WEIGHT"
#"3:62495388:C:T"	3	62495388	"C"	"T"	1

In [15]:
head(msp_ace_3)

  chm spos   epos   sgpos egpos n.snps AU003305.0 AU003305.1 AU0226302.0
1 3    19366 252714 0.00  0.17  137    0          0          0
2 3   252714 338658 0.17  0.29   60    0          0          0
3 3   338658 396570 0.29  0.55   30    0          0          0
4 3   396570 636663 0.55  0.93   55    0          0          0
5 3   636663 725777 0.93  0.99   30    0          0          0
6 3   725777 746086 0.99  1.04    5    0          0          0
  AU0226302.1 ⋯ DG1580.201.0 DG1580.201.1 DG1580.202.0 DG1580.202.1
1 0           ⋯ 1            1            0            0
2 0           ⋯ 1            1            0            0
3 0           ⋯ 1            1            0            0
4 0           ⋯ 1            1            0            0
5 0           ⋯ 1            1            0            0
6 0           ⋯ 1            1            0            0
  DG1580.301.0 DG1580.301.1 DG1228.202.0 DG1228.202.1 DG1228.302.0 DG1228.302.1
1 0            1            1            1            1            1
2 0            1            1            1            1            1
3 0            1            1            1            1            1
4 0            1            1            1            1            1
5 0            1            1            1            1            1
6 0            1            1            1            1            1

In [16]:
 snp_chunk <- msp_ace_3[msp_ace_3$spos <= 62495388 & msp_ace_3$epos >= 62495388, ]

In [17]:
snp_chunk

    chm spos     epos     sgpos egpos n.snps AU003305.0 AU003305.1 AU0226302.0
602 3   62419217 62602944 81.67 82.13 105    0          0          0
    AU0226302.1 ⋯ DG1580.201.0 DG1580.201.1 DG1580.202.0 DG1580.202.1
602 0           ⋯ 0            1            0            0
    DG1580.301.0 DG1580.301.1 DG1228.202.0 DG1228.202.1 DG1228.302.0
602 1            0            1            1            1
    DG1228.302.1
602 1

In [18]:
colnames(snp_chunk)

   [1] "chm"                "spos"               "epos"
   [4] "sgpos"              "egpos"              "n.snps"
   [7] "AU003305.0"         "AU003305.1"         "AU0226302.0"
  [10] "AU0226302.1"        "AU0226303.0"        "AU0226303.1"
  [13] "AU025304.0"         "AU025304.1"         "AU025804.0"
  [16] "AU025804.1"         "MN.308.0"           "MN.308.1"
  [19] "AU032904.0"         "AU032904.1"         "AU0416201.0"
  [22] "AU0416201.1"        "AU0416202.0"        "AU0416202.1"
  [25] "AU0416301.0"        "AU0416301.1"        "AU0416302.0"
  [28] "AU0416302.1"        "AU079405.0"         "AU079405.1"
  [31] "AU0889301.0"        "AU0889301.1"        "AU0889302.0"
  [34] "AU0889302.1"        "AU0906301.0"        "AU0906301.1"
  [37] "AU0906302.0"        "AU0906302.1"        "AU0925201.0"
  [40] "AU0925201.1"        "AU0925202.0"        "AU0925202.1"
  [43] "AU0925301.0"        "AU0925301.1"        "AU0925302.0"
  [46] "AU0925302.1"        "AU1230301.0"        "AU1230301.1"
  [49] "AU1230305.0"        "AU1230305.1"        "AU1265202.0"
  [52] "AU1265202.1"        "AU1362201.0"        "AU1362201.1"
  [55] "AU1362202.0"        "AU1362202.1"        "AU1362301.0"
  [58] "AU1362301.1"        "AU1365301.0"        "AU1365301.1"
  [61] "AU1402302.0"        "AU1402302.1"        "AU1438302.0"
  [64] "AU1438302.1"        "AU1438303.0"        "AU1438303.1"
  [67] "AU1441201.0"        "AU1441201.1"        "AU1441202.0"
  [70] "AU1441202.1"        "AU1441301.0"        "AU1441301.1"
  [73] "AU1441302.0"        "AU1441302.1"        "AU1454201.0"
  [76] "AU1454201.1"        "AU1481201.0"        "AU1481201.1"
  [79] "AU1481202.0"        "AU1481202.1"        "AU1481302.0"
  [82] "AU1481302.1"        "AU1481303.0"        "AU1481303.1"
  [85] "AU1524302.0"        "AU1524302.1"        "AU1537302.0"
  [88] "AU1537302.1"        "AU1537304.0"        "AU1537304.1"
  [91] "AU1560301.0"        "AU1560301.1"        "AU1560302.0"
  [94] "AU1560302.1"        "AU1560303.0"        "AU1560303.1"
  [97] "AU1563202.0"        "AU1563202.1"        "AU1563301.0"
 [100] "AU1563301.1"        "AU1563303.0"        "AU1563303.1"
 [103] "AU1572201.0"        "AU1572201.1"        "AU1572302.0"
 [106] "AU1572302.1"        "AU1582303.0"        "AU1582303.1"
 [109] "AU1640201.0"        "AU1640201.1"        "AU1684202.0"
 [112] "AU1684202.1"        "AU1697301.0"        "AU1697301.1"
 [115] "AU1697302.0"        "AU1697302.1"        "AU1718301.0"
 [118] "AU1718301.1"        "AU1741302.0"        "AU1741302.1"
 [121] "AU1741303.0"        "AU1741303.1"        "AU1741304.0"
 [124] "AU1741304.1"        "AU1741305.0"        "AU1741305.1"
 [127] "AU1745201.0"        "AU1745201.1"        "AU1745202.0"
 [130] "AU1745202.1"        "AU1745301.0"        "AU1745301.1"
 [133] "AU1749201.0"        "AU1749201.1"        "AU1749202.0"
 [136] "AU1749202.1"        "AU1749301.0"        "AU1749301.1"
 [139] "AU1749302.0"        "AU1749302.1"        "AU1762202.0"
 [142] "AU1762202.1"        "AU1802301.0"        "AU1802301.1"
 [145] "AU1802303.0"        "AU1802303.1"        "AU1810302.0"
 [148] "AU1810302.1"        "AU1810303.0"        "AU1810303.1"
 [151] "AU1822301.0"        "AU1822301.1"        "AU1832302.0"
 [154] "AU1832302.1"        "AU1849202.0"        "AU1849202.1"
 [157] "AU1850301.0"        "AU1850301.1"        "AU1850302.0"
 [160] "AU1850302.1"        "AU1885201.0"        "AU1885201.1"
 [163] "AU1885202.0"        "AU1885202.1"        "AU1885301.0"
 [166] "AU1885301.1"        "AU1885302.0"        "AU1885302.1"
 [169] "AU1887201.0"        "AU1887201.1"        "AU1887202.0"
 [172] "AU1887202.1"        "AU1887301.0"        "AU1887301.1"
 [175] "AU1887302.0"        "AU1887302.1"        "AU1898201.0"
 [178] "AU1898201.1"        "AU1898202.0"        "AU1898202.1"
 [181] "AU1898303.0"        "AU1898303.1"        "AU1898304.0"
 [184] "AU1898304.1"        "AU1898305.0"        "AU1898305.1"
 [187] "AU1900301.0"        "AU1900301.1"        "AU1900303.0"
 [190] "AU1900303.1"        "AU1903202.0"        "AU1903202.1"
 [193] "AU0636201.0"        "AU0636201.1"        "AU0636303.0"
 [196] "AU0636303.1"        "AU0636202.0"        "AU0636202.1"
 [199] "AU0691302.0"        "AU0691302.1"        "AU0636302.0"
 [202] "AU0636302.1"        "AU0691303.0"        "AU0691303.1"
 [205] "AU2063306.0"        "AU2063306.1"        "AU2063307.0"
 [208] "AU2063307.1"        "AU1951303.0"        "AU1951303.1"
 [211] "AU1951304.0"        "AU1951304.1"        "AU1436301.0"
 [214] "AU1436301.1"        "AU1436202.0"        "AU1436202.1"
 [217] "AU1436201.0"        "AU1436201.1"        "AU1250201.0"
 [220] "AU1250201.1"        "AU1250202.0"        "AU1250202.1"
 [223] "AU1250303.0"        "AU1250303.1"        "AU1250304.0"
 [226] "AU1250304.1"        "AU1042303.0"        "AU1042303.1"
 [229] "AU1042201.0"        "AU1042201.1"        "AU1042202.0"
 [232] "AU1042202.1"        "AU1314302.0"        "AU1314302.1"
 [235] "AU1314301.0"        "AU1314301.1"        "AU1314202.0"
 [238] "AU1314202.1"        "AU1314201.0"        "AU1314201.1"
 [241] "AU1501201.0"        "AU1501201.1"        "AU1501302.0"
 [244] "AU1501302.1"        "AU1501202.0"        "AU1501202.1"
 [247] "AU1633202.0"        "AU1633202.1"        "AU1633302.0"
 [250] "AU1633302.1"        "AU1633201.0"        "AU1633201.1"
 [253] "AU1508201.0"        "AU1508201.1"        "AU1508202.0"
 [256] "AU1508202.1"        "AU1508301.0"        "AU1508301.1"
 [259] "AU1508302.0"        "AU1508302.1"        "AU1433303.0"
 [262] "AU1433303.1"        "AU1433204.0"        "AU1433204.1"
 [265] "AU1433201.0"        "AU1433201.1"        "AU1433305.0"
 [268] "AU1433305.1"        "AU1433304.0"        "AU1433304.1"
 [271] "AU2137304.0"        "AU2137304.1"        "AU1757301.0"
 [274] "AU1757301.1"        "AU1757302.0"        "AU1757302.1"
 [277] "AU2137305.0"        "AU2137305.1"        "AU1781201.0"
 [280] "AU1781201.1"        "AU1781202.0"        "AU1781202.1"
 [283] "AU1781302.0"        "AU1781302.1"        "AU1781303.0"
 [286] "AU1781303.1"        "AU1781304.0"        "AU1781304.1"
 [289] "AU1794302.0"        "AU1794302.1"        "AU1794202.0"
 [292] "AU1794202.1"        "AU1794301.0"        "AU1794301.1"
 [295] "AU1794201.0"        "AU1794201.1"        "AU2107302.0"
 [298] "AU2107302.1"        "AU1930303.0"        "AU1930303.1"
 [301] "AU2107303.0"        "AU2107303.1"        "AU1930301.0"
 [304] "AU1930301.1"        "AU1930201.0"        "AU1930201.1"
 [307] "AU0865201.0"        "AU0865201.1"        "AU0865202.0"
 [310] "AU0865202.1"        "AU0865301.0"        "AU0865301.1"
 [313] "AU0865302.0"        "AU0865302.1"        "AU0865303.0"
 [316] "AU0865303.1"        "AU0865304.0"        "AU0865304.1"
 [319] "AU1956302.0"        "AU1956302.1"        "AU1956303.0"
 [322] "AU1956303.1"        "AU1930202.0"        "AU1930202.1"
 [325] "AU1930302.0"        "AU1930302.1"        "AU1930304.0"
 [328] "AU1930304.1"        "AU1948301.0"        "AU1948301.1"
 [331] "AU1948302.0"        "AU1948302.1"        "AU2015201.0"
 [334] "AU2015201.1"        "AU2015202.0"        "AU2015202.1"
 [337] "AU2015301.0"        "AU2015301.1"        "AU2015302.0"
 [340] "AU2015302.1"        "AU2454301.0"        "AU2454301.1"
 [343] "AU2348202.0"        "AU2348202.1"        "AU2348301.0"
 [346] "AU2348301.1"        "AU2348303.0"        "AU2348303.1"
 [349] "AU1638301.0"        "AU1638301.1"        "AU1969202.0"
 [352] "AU1969202.1"        "AU1969303.0"        "AU1969303.1"
 [355] "AU1857202.0"        "AU1857202.1"        "AU1857301.0"
 [358] "AU1857301.1"        "AU1042304.0"        "AU1042304.1"
 [361] "AU1857201.0"        "AU1857201.1"        "AU2524202.0"
 [364] "AU2524202.1"        "AU1729201.0"        "AU1729201.1"
 [367] "AU1729202.0"        "AU1729202.1"        "AU1729301.0"
 [370] "AU1729301.1"        "AU1729302.0"        "AU1729302.1"
 [373] "AU1401201.0"        "AU1401201.1"        "AU1401202.0"
 [376] "AU1401202.1"        "AU1401302.0"        "AU1401302.1"
 [379] "AU1401303.0"        "AU1401303.1"        "AU2524301.0"
 [382] "AU2524301.1"        "AU2524302.0"        "AU2524302.1"
 [385] "AU2524304.0"        "AU2524304.1"        "AU2566301.0"
 [388] "AU2566301.1"        "AU1948201.0"        "AU1948201.1"
 [391] "AU1948202.0"        "AU1948202.1"        "AU1772201.0"
 [394] "AU1772201.1"        "AU1772202.0"        "AU1772202.1"
 [397] "AU1772301.0"        "AU1772301.1"        "AU1772302.0"
 [400] "AU1772302.1"        "AU1772303.0"        "AU1772303.1"
 [403] "AU2566302.0"        "AU2566302.1"        "AU2125202.0"
 [406] "AU2125202.1"        "AU2125301.0"        "AU2125301.1"
 [409] "AU2125302.0"        "AU2125302.1"        "AU2125303.0"
 [412] "AU2125303.1"        "AU2350201.0"        "AU2350201.1"
 [415] "AU2350202.0"        "AU2350202.1"        "AU2350302.0"
 [418] "AU2350302.1"        "AU2007201.0"        "AU2007201.1"
 [421] "AU2007202.0"        "AU2007202.1"        "AU2007302.0"
 [424] "AU2007302.1"        "AU2109301.0"        "AU2109301.1"
 [427] "AU2109302.0"        "AU2109302.1"        "AU2103302.0"
 [430] "AU2103302.1"        "AU2103301.0"        "AU2103301.1"
 [433] "AU2351301.0"        "AU2351301.1"        "AU2382201.0"
 [436] "AU2382201.1"        "AU2382301.0"        "AU2382301.1"
 [439] "AU2382302.0"        "AU2382302.1"        "AU2382303.0"
 [442] "AU2382303.1"        "AU2606202.0"        "AU2606202.1"
 [445] "AU2578302.0"        "AU2578302.1"        "AU2524201.0"
 [448] "AU2524201.1"        "AU2404201.0"        "AU2404201.1"
 [451] "AU2518202.0"        "AU2518202.1"        "AU2123201.0"
 [454] "AU2123201.1"        "AU2123202.0"        "AU2123202.1"
 [457] "AU2123301.0"        "AU2123301.1"        "AU2123302.0"
 [460] "AU2123302.1"        "AU2137201.0"        "AU2137201.1"
 [463] "AU2137203.0"        "AU2137203.1"        "AU2137303.0"
 [466] "AU2137303.1"        "AU1997201.0"        "AU1997201.1"
 [469] "AU1997202.0"        "AU1997202.1"        "AU1997301.0"
 [472] "AU1997301.1"        "AU1997302.0"        "AU1997302.1"
 [475] "AU1833202.0"        "AU1833202.1"        "AU1778202.0"
 [478] "AU1778202.1"        "AU1778301.0"        "AU1778301.1"
 [481] "AU1942302.0"        "AU1942302.1"        "AU1942301.0"
 [484] "AU1942301.1"        "AU1942202.0"        "AU1942202.1"
 [487] "AU1942201.0"        "AU1942201.1"        "AU1924201.0"
 [490] "AU1924201.1"        "AU1924202.0"        "AU1924202.1"
 [493] "AU1924301.0"        "AU1924301.1"        "AU1924302.0"
 [496] "AU1924302.1"        "AU1924303.0"        "AU1924303.1"
 [499] "AU1784201.0"        "AU1784201.1"        "AU1784202.0"
 [502] "AU1784202.1"        "AU1784301.0"        "AU1784301.1"
 [505] "AU1784302.0"        "AU1784302.1"        "AU1732201.0"
 [508] "AU1732201.1"        "AU1732202.0"        "AU1732202.1"
 [511] "AU1732302.0"        "AU1732302.1"        "AU1732303.0"
 [514] "AU1732303.1"        "AU1820312.0"        "AU1820312.1"
 [517] "AU1858201.0"        "AU1858201.1"        "AU1858202.0"
 [520] "AU1858202.1"        "AU1858301.0"        "AU1858301.1"
 [523] "AU1858302.0"        "AU1858302.1"        "AU1858303.0"
 [526] "AU1858303.1"        "AU1858304.0"        "AU1858304.1"
 [529] "AU1836201.0"        "AU1836201.1"        "AU1836202.0"
 [532] "AU1836202.1"        "AU1836301.0"        "AU1836301.1"
 [535] "AU1836302.0"        "AU1836302.1"        "AU1765201.0"
 [538] "AU1765201.1"        "AU1765202.0"        "AU1765202.1"
 [541] "AU1765301.0"        "AU1765301.1"        "AU1686201.0"
 [544] "AU1686201.1"        "AU1686202.0"        "AU1686202.1"
 [547] "AU1686301.0"        "AU1686301.1"        "AU1686302.0"
 [550] "AU1686302.1"        "AU1765302.0"        "AU1765302.1"
 [553] "AU1576201.0"        "AU1576201.1"        "AU1967304.0"
 [556] "AU1967304.1"        "AU2032201.0"        "AU2032201.1"
 [559] "AU2032202.0"        "AU2032202.1"        "AU2032301.0"
 [562] "AU2032301.1"        "AU2032302.0"        "AU2032302.1"
 [565] "AU2094201.0"        "AU2094201.1"        "AU2094202.0"
 [568] "AU2094202.1"        "AU2094301.0"        "AU2094301.1"
 [571] "AU2094302.0"        "AU2094302.1"        "AU1371201.0"
 [574] "AU1371201.1"        "AU1371202.0"        "AU1371202.1"
 [577] "AU2109201.0"        "AU2109201.1"        "AU2109202.0"
 [580] "AU2109202.1"        "AU1967201.0"        "AU1967201.1"
 [583] "AU1727202.0"        "AU1727202.1"        "AU1727302.0"
 [586] "AU1727302.1"        "AU1727303.0"        "AU1727303.1"
 [589] "AU1638201.0"        "AU1638201.1"        "AU1739302.0"
 [592] "AU1739302.1"        "AU1638202.0"        "AU1638202.1"
 [595] "AU2581201.0"        "AU2581201.1"        "AU2581202.0"
 [598] "AU2581202.1"        "AU2581302.0"        "AU2581302.1"
 [601] "AU2557202.0"        "AU2557202.1"        "AU2557301.0"
 [604] "AU2557301.1"        "AU1664202.0"        "AU1664202.1"
 [607] "AU2156301.0"        "AU2156301.1"        "AU2156302.0"
 [610] "AU2156302.1"        "AU2087301.0"        "AU2087301.1"
 [613] "AU2087302.0"        "AU2087302.1"        "AU1553301.0"
 [616] "AU1553301.1"        "AU2312201.0"        "AU2312201.1"
 [619] "AU2312202.0"        "AU2312202.1"        "AU2312301.0"
 [622] "AU2312301.1"        "AU2312302.0"        "AU2312302.1"
 [625] "AU2370201.0"        "AU2370201.1"        "AU2370202.0"
 [628] "AU2370202.1"        "AU2370301.0"        "AU2370301.1"
 [631] "AU1638303.0"        "AU1638303.1"        "AU1709201.0"
 [634] "AU1709201.1"        "AU1709202.0"        "AU1709202.1"
 [637] "AU1709301.0"        "AU1709301.1"        "AU1739201.0"
 [640] "AU1739201.1"        "AU1371303.0"        "AU1371303.1"
 [643] "AU1835201.0"        "AU1835201.1"        "AU1835202.0"
 [646] "AU1835202.1"        "AU1835302.0"        "AU1835302.1"
 [649] "AU1835303.0"        "AU1835303.1"        "AU1576202.0"
 [652] "AU1576202.1"        "AU1576301.0"        "AU1576301.1"
 [655] "AU1576302.0"        "AU1576302.1"        "AU1576303.0"
 [658] "AU1576303.1"        "AU1967202.0"        "AU1967202.1"
 [661] "AU1967301.0"        "AU1967301.1"        "AU1633303.0"
 [664] "AU1633303.1"        "AU2018305.0"        "AU2018305.1"
 [667] "AU2190303.0"        "AU2190303.1"        "AU2158301.0"
 [670] "AU2158301.1"        "AU2158302.0"        "AU2158302.1"
 [673] "AU2606301.0"        "AU2606301.1"        "AU2606302.0"
 [676] "AU2606302.1"        "AU2606303.0"        "AU2606303.1"
 [679] "AU2190302.0"        "AU2190302.1"        "AU1957201.0"
 [682] "AU1957201.1"        "AU1820211.0"        "AU1820211.1"
 [685] "AU2348302.0"        "AU2348302.1"        "AU1642302.0"
 [688] "AU1642302.1"        "AU1838303.0"        "AU1838303.1"
 [691] "AU1647303.0"        "AU1647303.1"        "AU0347301.0"
 [694] "AU0347301.1"        "AU1873201.0"        "AU1873201.1"
 [697] "AU1873202.0"        "AU1873202.1"        "AU1873302.0"
 [700] "AU1873302.1"        "AU1873303.0"        "AU1873303.1"
 [703] "AU1993202.0"        "AU1993202.1"        "AU1993301.0"
 [706] "AU1993301.1"        "AU1993302.0"        "AU1993302.1"
 [709] "AU0883303.0"        "AU0883303.1"        "AU1647201.0"
 [712] "AU1647201.1"        "AU1647202.0"        "AU1647202.1"
 [715] "AU1647302.0"        "AU1647302.1"        "AU1993201.0"
 [718] "AU1993201.1"        "AU1593301.0"        "AU1593301.1"
 [721] "AU1593302.0"        "AU1593302.1"        "AU1593303.0"
 [724] "AU1593303.1"        "AU0347302.0"        "AU0347302.1"
 [727] "AU0347303.0"        "AU0347303.1"        "AU1983303.0"
 [730] "AU1983303.1"        "AU1642201.0"        "AU1642201.1"
 [733] "AU1642202.0"        "AU1642202.1"        "AU1642301.0"
 [736] "AU1642301.1"        "AU1642304.0"        "AU1642304.1"
 [739] "AU1968201.0"        "AU1968201.1"        "AU1968202.0"
 [742] "AU1968202.1"        "AU1968301.0"        "AU1968301.1"
 [745] "AU1968302.0"        "AU1968302.1"        "AU2038201.0"
 [748] "AU2038201.1"        "AU2038202.0"        "AU2038202.1"
 [751] "AU2038301.0"        "AU2038301.1"        "AU2038302.0"
 [754] "AU2038302.1"        "AU2038303.0"        "AU2038303.1"
 [757] "AU2052201.0"        "AU2052201.1"        "AU2052202.0"
 [760] "AU2052202.1"        "AU2052301.0"        "AU2052301.1"
 [763] "AU2052302.0"        "AU2052302.1"        "AU2052303.0"
 [766] "AU2052303.1"        "AU2052304.0"        "AU2052304.1"
 [769] "AU1696201.0"        "AU1696201.1"        "AU1696202.0"
 [772] "AU1696202.1"        "AU1696302.0"        "AU1696302.1"
 [775] "AU1696303.0"        "AU1696303.1"        "AU1696304.0"
 [778] "AU1696304.1"        "AU1838201.0"        "AU1838201.1"
 [781] "AU1838203.0"        "AU1838203.1"        "AU1838302.0"
 [784] "AU1838302.1"        "AU1838304.0"        "AU1838304.1"
 [787] "AU1436302.0"        "AU1436302.1"        "AU2922202.0"
 [790] "AU2922202.1"        "AU2868202.0"        "AU2868202.1"
 [793] "AU2994301.0"        "AU2994301.1"        "AU2903302.0"
 [796] "AU2903302.1"        "AU2891302.0"        "AU2891302.1"
 [799] "AU2722301.0"        "AU2722301.1"        "AU1899202.0"
 [802] "AU1899202.1"        "AU2031301.0"        "AU2031301.1"
 [805] "AU2031302.0"        "AU2031302.1"        "AU2184301.0"
 [808] "AU2184301.1"        "AU2184302.0"        "AU2184302.1"
 [811] "AU2044303.0"        "AU2044303.1"        "AU3084202.0"
 [814] "AU3084202.1"        "AU1500201.0"        "AU1500201.1"
 [817] "AU3127202.0"        "AU3127202.1"        "AU3084304.0"
 [820] "AU3084304.1"        "AU2963202.0"        "AU2963202.1"
 [823] "AU2488202.0"        "AU2488202.1"        "AU2184202.0"
 [826] "AU2184202.1"        "AU2432201.0"        "AU2432201.1"
 [829] "AU2855303.0"        "AU2855303.1"        "AU1721202.0"
 [832] "AU1721202.1"        "AU2807301.0"        "AU2807301.1"
 [835] "AU3082304.0"        "AU3082304.1"        "AU2433202.0"
 [838] "AU2433202.1"        "AU2403305.0"        "AU2403305.1"
 [841] "AU2827201.0"        "AU2827201.1"        "AU2229201.0"
 [844] "AU2229201.1"        "AU2994202.0"        "AU2994202.1"
 [847] "AU2485304.0"        "AU2485304.1"        "AU2522301.0"
 [850] "AU2522301.1"        "AU2722202.0"        "AU2722202.1"
 [853] "AU2868302.0"        "AU2868302.1"        "AU2774201.0"
 [856] "AU2774201.1"        "AU2229302.0"        "AU2229302.1"
 [859] "AU3017301.0"        "AU3017301.1"        "AU2606201.0"
 [862] "AU2606201.1"        "AU2278301.0"        "AU2278301.1"
 [865] "AU3017201.0"        "AU3017201.1"        "AU2783302.0"
 [868] "AU2783302.1"        "AU2846302.0"        "AU2846302.1"
 [871] "AU2867202.0"        "AU2867202.1"        "AU2855304.0"
 [874] "AU2855304.1"        "AU2404202.0"        "AU2404202.1"
 [877] "AU2404301.0"        "AU2404301.1"        "AU2404302.0"
 [880] "AU2404302.1"        "AU2948302.0"        "AU2948302.1"
 [883] "AU2104302.0"        "AU2104302.1"        "AU3146201.0"
 [886] "AU3146201.1"        "AU1500202.0"        "AU1500202.1"
 [889] "AU1899301.0"        "AU1899301.1"        "AU3094303.0"
 [892] "AU3094303.1"        "AU2991201.0"        "AU2991201.1"
 [895] "AU3094201.0"        "AU3094201.1"        "AU3127302.0"
 [898] "AU3127302.1"        "AU1500305.0"        "AU1500305.1"
 [901] "AU1500306.0"        "AU1500306.1"        "AU2437302.0"
 [904] "AU2437302.1"        "AU2522201.0"        "AU2522201.1"
 [907] "AU2522303.0"        "AU2522303.1"        "AU2437201.0"
 [910] "AU2437201.1"        "AU2922302.0"        "AU2922302.1"
 [913] "AU2994303.0"        "AU2994303.1"        "AU2863301.0"
 [916] "AU2863301.1"        "AU2266301.0"        "AU2266301.1"
 [919] "AU2266302.0"        "AU2266302.1"        "AU0965303.0"
 [922] "AU0965303.1"        "AU2487301.0"        "AU2487301.1"
 [925] "AU2863202.0"        "AU2863202.1"        "AU2487303.0"
 [928] "AU2487303.1"        "AU2989201.0"        "AU2989201.1"
 [931] "AU2160201.0"        "AU2160201.1"        "AU2160202.0"
 [934] "AU2160202.1"        "AU2160301.0"        "AU2160301.1"
 [937] "AU2160302.0"        "AU2160302.1"        "AU2950201.0"
 [940] "AU2950201.1"        "AU2950202.0"        "AU2950202.1"
 [943] "AU2950301.0"        "AU2950301.1"        "AU2950302.0"
 [946] "AU2950302.1"        "AU3019201.0"        "AU3019201.1"
 [949] "AU3019202.0"        "AU3019202.1"        "AU3019302.0"

In [28]:
# Get all column names
col_names <- colnames(snp_chunk)

In [29]:
# Find columns that end in .0 or .1
col_0 <- grep("\\.0$", col_names, value = TRUE)
col_1 <- grep("\\.1$", col_names, value = TRUE)

# Strip suffix to get base names
base_names_0 <- sub("\\.0$", "", col_0)
base_names_1 <- sub("\\.1$", "", col_1)

# Find common base names (i.e., ones that have both .0 and .1)
shared_base <- intersect(base_names_0, base_names_1)

In [31]:
# Initialize named vector to store sums
sum_vector <- setNames(numeric(length(shared_base)), shared_base)

# Calculate sums for each base
for (base in shared_base) {
  col0 <- paste0(base, ".0")
  col1 <- paste0(base, ".1")
  sum_vector[base] <- sum(snp_chunk[[col0]] + snp_chunk[[col1]], na.rm = TRUE)
}

# Convert to data frame with ID and SUM as columns
sum_df <- data.frame(
  ID = names(sum_vector),
  SUM = as.numeric(sum_vector),
  stringsAsFactors = FALSE
)

head(sum_df)

  ID        SUM
1 AU003305  0
2 AU0226302 0
3 AU0226303 0
4 AU025304  0
5 AU025804  0
6 MN.308    0

In [32]:
table(sum_df$SUM)

   0    1    2
1395  470  747

In [ ]:
write.csv(sum_df, "ace_rs1452075_pos_counts.csv")