In [1]:
library(tidyverse)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.6     ✔ purrr   0.3.4
✔ tibble  3.1.7     ✔ dplyr   1.0.7
✔ tidyr   1.1.4     ✔ stringr 1.4.0
✔ readr   2.0.2     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [3]:
psam_df <- read.table("/u/project/geschwind/shared/GenomicDatasets-processed/Imputed/total_vcfs_r2_0.8/combined/merged_output_2.psam")

In [4]:
head(psam_df)

  V1        V2
1 AU003305  NA
2 AU0226302 NA
3 AU0226303 NA
4 AU025304  NA
5 AU025804  NA
6 MN.308    NA

In [5]:
gia <- read.table("/u/home/a/afcarrol/project-pasaniuc/Projects/20240318_ACE_SPARK_SAIGE_prep/ace_afr_gia.txt")

In [7]:
head(gia)

  V1
1 702-B-80313.01_702-B-80313.01
2 702-B-80313.02_702-B-80313.02
3 702-B-80313.03_702-B-80313.03
4 702-B-80349.03_702-B-80349.03
5 702-C-80366.01_702-C-80366.01
6 702-C-80366.02_702-C-80366.02

In [6]:
iid_list_split <- gia %>%
  mutate(original_names = V1) %>%
  separate(V1, into = c("new_name", "dup"), sep = "_")

Warning message:
“Expected 2 pieces. Missing pieces filled with `NA` in 639 rows [1147, 1148, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, ...].”

In [7]:
ace_covar <- read.csv("ace_covar.csv")

In [11]:
head(ace_covar)

  vcf.ID                        IID            FID         SEX dx age PC1
1 702-A-80310.01_702-A-80310.01 702-A-80310.01 702-A-80310 1   NA NA  -59.20396
2 702-A-80310.02_702-A-80310.02 702-A-80310.02 702-A-80310 2   NA NA  -70.83652
3 702-A-80310.03_702-A-80310.03 702-A-80310.03 702-A-80310 1   NA NA  -65.44799
4 702-A-80310.04_702-A-80310.04 702-A-80310.04 702-A-80310 1   NA NA  -66.49899
5 702-A-80310.05_702-A-80310.05 702-A-80310.05 702-A-80310 2   NA NA  -64.56624
6 702-A-80330.01_702-A-80330.01 702-A-80330.01 702-A-80330 1   NA NA  -69.06192
  PC2       PC3       PC4      ... PC13        PC14        PC15     PC16
1 21.898834 -74.07577 63.78452 ... -6.49634460 -0.06024645 7.237338 -52.26812
2 64.028260 -53.23033 11.79616 ...  1.29570805  0.46195499 1.806164 -28.97094
3 39.064043 -65.51733 41.20630 ... -3.72554381  1.32306199 4.095155 -44.62658
4 46.010683 -63.47658 35.34593 ... -0.01174978  2.31100273 7.981447 -44.73312
5 37.548055 -71.61951 46.30474 ... -2.03119072  1.00376214 4.425171 -43.74187
6  4.943752 -97.16606 76.97857 ... -7.97318990 -2.45305754 5.905170 -57.25083
  PC17      PC18       PC19       PC20       data ancestry
1 -14.34788 -13.893078  0.5879248 10.1966165 ace  AMR
2 -13.70503   4.355163 -1.6504476 -0.2859964 ace  AMR
3 -14.73959  -1.790906  0.8654015 10.9098518 ace  AMR
4 -13.00900  -9.808721 -4.8037655  5.1445242 ace  AMR
5 -19.23304  -3.839576  0.4724755  5.1736369 ace  AMR
6 -23.27042   5.275870  2.8850064 -1.4868289 ace  AMR

In [8]:
table(ace_covar$ancestry)

         AFR          AMR          EAS          EUR          SAS Unclassified
        1146          236           53         1059           15          103

In [10]:
ace_afr <- ace_covar[ace_covar$ancestry == "AFR",]

In [11]:
dim(ace_afr)

[1] 1146   28

In [12]:
sum(psam_df$V1 %in% ace_afr$IID)

[1] 1145

In [13]:
sub_list <- psam_df[psam_df$V1 %in% ace_afr$IID,]$V1

In [18]:
head(sub_list)

[1] "AU2107302" "AU2107303" "AU2103302" "AU2103301" "AU1983303" "AU2403305"

In [14]:
length(sub_list)

[1] 1145

In [20]:
# Write the IID list to a text file
write.table(sub_list, file = "ace_afr_sub.txt", row.names = FALSE, col.names = FALSE, quote = FALSE)

In [15]:
ace_saige <- read.csv("/u/project/geschwind/shared/GenomicDatasets-processed/Imputed/total_vcfs_r2_0.8/combined/ace_afr_gia_sub/covar_files/ace_saige_covar.csv")

In [29]:
head(ace_saige)

  IID            ASD Age Sex PC1       PC2        PC3        PC4
1 702-B-80313.01 NA  NA  1   184.65192  -5.891468  -2.900146  -2.657747
2 702-B-80313.02 NA  NA  2   153.78163   8.532198  -5.001013  -3.857924
3 702-B-80313.03 NA  NA  1   162.18693   5.431722  -4.472228  -4.918310
4 702-B-80349.03 NA  NA  1    65.24571  53.317234 -10.116277 -22.077099
5 702-C-80366.01 NA  NA  1   201.09601 -12.003891  -1.243008   0.478470
6 702-C-80366.02 NA  NA  2   176.60745  -2.010892  -1.834840  -2.793795
  PC5        PC6       PC7         PC8        PC9        PC10
1 -3.9755161 1.1435332  -1.8579833   6.073716 -1.2284604 -0.4025226
2 -5.9251680 0.6189638  -1.0352931   8.592505 -0.9892908 -2.4176311
3 -5.0655801 0.6699603  -0.2040976   6.569552 -0.3008778 -2.1752027
4  0.5976043 0.7694011  -3.7385065   6.517439 -0.8203326 -8.9293064
5 -4.4707328 0.6042325 -16.0419716  30.884951  1.2451292  5.3640178
6  7.9995680 0.4965067 -38.5122672 -31.951022 -1.5847601 -2.9359645

In [16]:
# Elements in list1 but not in list2
in_csv_only <- ace_saige$IID[!(ace_saige$IID %in% sub_list)]

# Elements in list2 but not in list1
in_vcf_only <- sub_list[!(sub_list %in% ace_saige$IID)]

In [17]:
in_csv_only

character(0)

In [18]:
in_vcf_only

[1] "SAU0082"

In [21]:
my_list <- sub_list[sub_list != 'SAU0082']

In [22]:
my_list[!(my_list %in% ace_saige$IID)]

character(0)

In [23]:
write.table(my_list, file = "ace_afr_sub.txt", row.names = FALSE, col.names = FALSE, quote = FALSE)