In [1]:
library(data.table)

In [3]:
list.files()

[1] "spark_hm3_unrelated.grm.gz" "spark_hm3_unrelated.grm.id"
[3] "spark_hm3_unrelated.log"    "Untitled.ipynb"

In [7]:
ids <- as.data.frame(fread("spark_hm3_unrelated.grm.id", header=F))

In [8]:
head(ids)

  V1        V2
1 SF0000017 SP0000017
2 SF0000027 SP0000051
3 SF0000027 SP0000241
4 SF0000030 SP0000030
5 SF0000033 SP0000033
6 SF0000057 SP0000057

In [9]:
length(unique(ids$V2))

[1] 33468

In [10]:
shm3 <- fread("spark_hm3_unrelated.grm.gz",nrows=10)

In [11]:
shm3

   V1 V2 V3     V4
1  1  1  636516  1.0124830000
2  2  1  636516 -0.0054423330
3  2  2  636516  1.0143890000
4  3  1  636516  0.0047735250
5  3  2  636516  0.0084430390
6  3  3  636516  1.0092280000
7  4  1  636516 -0.0002733878
8  4  2  636516 -0.0006341935
9  4  3  636516  0.0045967890
10 4  4  636516  0.9928838000

In [12]:
unre_pop <- unique(ids$V2)

In [13]:
head(unre_pop)

[1] "SP0000017" "SP0000051" "SP0000241" "SP0000030" "SP0000033" "SP0000057"

In [14]:
write.csv(unre_pop, "unrelated_pop.csv")