In [1]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [3]:
getwd()

[1] "/u/project/pasaniuc/afcarrol/Projects/20240423_ace_partial_hm3"

In [4]:
# Set the directory path containing the files
directory_path <- "/u/project/pasaniuc/afcarrol/Projects/20240423_ace_partial_hm3/rfmix_out/"
# Initialize an empty data frame to store the results
result <- data.frame()

In [5]:
# Loop through files from ace_chr1 to ace_chr22
for (chr in 1:22) {
    

  # Construct the file path
  file_path <- paste0(directory_path, "chr", chr, ".rfmix.Q")
  print(file_path)
  # Read the data from the current file
  data <- read.table(file_path, header = F, sep = "\t")
  colnames(data) <- c("IID", "CEU", "YRI")
  # Combine the results for each ancestry (ANC1 and ANC2)
  result <- rbind(result, data)
}

[1] "/u/project/pasaniuc/afcarrol/Projects/20240423_ace_partial_hm3/rfmix_out/chr1.rfmix.Q"
[1] "/u/project/pasaniuc/afcarrol/Projects/20240423_ace_partial_hm3/rfmix_out/chr2.rfmix.Q"
[1] "/u/project/pasaniuc/afcarrol/Projects/20240423_ace_partial_hm3/rfmix_out/chr3.rfmix.Q"
[1] "/u/project/pasaniuc/afcarrol/Projects/20240423_ace_partial_hm3/rfmix_out/chr4.rfmix.Q"
[1] "/u/project/pasaniuc/afcarrol/Projects/20240423_ace_partial_hm3/rfmix_out/chr5.rfmix.Q"
[1] "/u/project/pasaniuc/afcarrol/Projects/20240423_ace_partial_hm3/rfmix_out/chr6.rfmix.Q"
[1] "/u/project/pasaniuc/afcarrol/Projects/20240423_ace_partial_hm3/rfmix_out/chr7.rfmix.Q"
[1] "/u/project/pasaniuc/afcarrol/Projects/20240423_ace_partial_hm3/rfmix_out/chr8.rfmix.Q"
[1] "/u/project/pasaniuc/afcarrol/Projects/20240423_ace_partial_hm3/rfmix_out/chr9.rfmix.Q"
[1] "/u/project/pasaniuc/afcarrol/Projects/20240423_ace_partial_hm3/rfmix_out/chr10.rfmix.Q"
[1] "/u/project/pasaniuc/afcarrol/Projects/20240423_ace_partial_hm3/rfmix_out/chr11.rfmix.Q"
[1] "/u/project/pasaniuc/afcarrol/Projects/20240423_ace_partial_hm3/rfmix_out/chr12.rfmix.Q"
[1] "/u/project/pasaniuc/afcarrol/Projects/20240423_ace_partial_hm3/rfmix_out/chr13.rfmix.Q"
[1] "/u/project/pasaniuc/afcarrol/Projects/20240423_ace_partial_hm3/rfmix_out/chr14.rfmix.Q"
[1] "/u/project/pasaniuc/afcarrol/Projects/20240423_ace_partial_hm3/rfmix_out/chr15.rfmix.Q"
[1] "/u/project/pasaniuc/afcarrol/Projects/20240423_ace_partial_hm3/rfmix_out/chr16.rfmix.Q"
[1] "/u/project/pasaniuc/afcarrol/Projects/20240423_ace_partial_hm3/rfmix_out/chr17.rfmix.Q"
[1] "/u/project/pasaniuc/afcarrol/Projects/20240423_ace_partial_hm3/rfmix_out/chr18.rfmix.Q"
[1] "/u/project/pasaniuc/afcarrol/Projects/20240423_ace_partial_hm3/rfmix_out/chr19.rfmix.Q"
[1] "/u/project/pasaniuc/afcarrol/Projects/20240423_ace_partial_hm3/rfmix_out/chr20.rfmix.Q"
[1] "/u/project/pasaniuc/afcarrol/Projects/20240423_ace_partial_hm3/rfmix_out/chr21.rfmix.Q"
[1] "/u/project/pasaniuc/afcarrol/Projects/20240423_ace_partial_hm3/rfmix_out/chr22.rfmix.Q"

In [6]:
# Sum the scores across all chromosomes for each individual by ancestry
final_result <- result %>%
  group_by(IID) %>%
  summarize(
    CEU_avg = mean(CEU),
    YRI_avg = mean(YRI)
  )

In [8]:
head(final_result)

  IID            CEU_avg   YRI_avg
1 702-A-80310.01 0.9415055 0.05849455
2 702-A-80310.02 0.9827005 0.01729955
3 702-A-80310.03 0.9604350 0.03956500
4 702-A-80310.04 0.9670764 0.03292364
5 702-A-80310.05 0.9534959 0.04650409
6 702-A-80330.01 0.9455314 0.05446864

In [9]:
range(final_result$YRI_avg)

[1] 0.00000 0.99948

In [10]:
write_csv(final_result, "ace_hm3_anc_prop.csv")

In [12]:
# Set the directory path containing the files
directory_path <- "/u/home/a/afcarrol/project-pasaniuc/Projects/20240423_ace_partial_hm3/part_pgs/"
# Initialize an empty data frame to store the results
result <- data.frame()

In [13]:

# Loop through files from ace_chr1 to ace_chr22
for (chr in 1:22) {
    
#    chr <- 1
  # Construct the file path
  file_path <- paste0(directory_path, "chr", chr, ".sample_pgs.tsv")
  print(file_path)
  # Read the data from the current file
  data <- read.table(file_path, header = TRUE, , sep = "\t")
  
  # Combine the results for each ancestry (ANC1 and ANC2)
  result <- rbind(result, data)
}

[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240423_ace_partial_hm3/part_pgs/chr1.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240423_ace_partial_hm3/part_pgs/chr2.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240423_ace_partial_hm3/part_pgs/chr3.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240423_ace_partial_hm3/part_pgs/chr4.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240423_ace_partial_hm3/part_pgs/chr5.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240423_ace_partial_hm3/part_pgs/chr6.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240423_ace_partial_hm3/part_pgs/chr7.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240423_ace_partial_hm3/part_pgs/chr8.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240423_ace_partial_hm3/part_pgs/chr9.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240423_ace_partial_hm3/part_pgs/chr10.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240423_ace_partial_hm3/part_pgs/chr11.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240423_ace_partial_hm3/part_pgs/chr12.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240423_ace_partial_hm3/part_pgs/chr13.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240423_ace_partial_hm3/part_pgs/chr14.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240423_ace_partial_hm3/part_pgs/chr15.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240423_ace_partial_hm3/part_pgs/chr16.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240423_ace_partial_hm3/part_pgs/chr17.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240423_ace_partial_hm3/part_pgs/chr18.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240423_ace_partial_hm3/part_pgs/chr19.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240423_ace_partial_hm3/part_pgs/chr20.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240423_ace_partial_hm3/part_pgs/chr21.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240423_ace_partial_hm3/part_pgs/chr22.sample_pgs.tsv"

In [14]:
final_result <- result %>%
  group_by(indiv) %>%
  summarize(
    ANC1_sum = sum(ANC1, na.rm = TRUE),
    ANC2_sum = sum(ANC2, na.rm = TRUE)
  )

In [16]:
head(final_result)

  indiv          ANC1_sum   ANC2_sum
1 702-A-80310.01 -0.3079798  0.1753440
2 702-A-80310.02 -4.0489320 -0.4398965
3 702-A-80310.03 -1.0007972 -0.2757587
4 702-A-80310.04 -1.5113513 -0.2203894
5 702-A-80310.05 -3.5890345  0.2582693
6 702-A-80330.01 -1.4528586 -0.1340971

In [18]:
dim(final_result)

[1] 2612    3

In [19]:
final_result$total_pgs <- final_result$ANC1_sum+final_result$ANC2_sum

In [21]:
write_csv(final_result, "ace_hm3_anc_pgs.csv")