In [1]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
ace_snps <- read.table("plink2.snplist")

In [3]:
head(ace_snps)

  V1
1 chr10:12040:G:A
2 chr10:14470:C:T
3 chr10:31093:GAC:G
4 chr10:36953:G:C
5 chr10:37005:C:A
6 chr10:40467:A:C

In [3]:
hm3_snps <- read.table("../20230117_spark_pca_update/hm3_snp_pos.txt")

In [4]:
head(hm3_snps)

  V1
1 1:817341
2 1:818802
3 1:825532
4 1:833068
5 1:843942
6 1:903175

In [14]:
ace_snps$V2 <- gsub("^chr", "", gsub("^(chr[^:]+:[^:]+):.*", "\\1", ace_snps$V1))

In [15]:
head(ace_snps)

  V1                V2
1 chr10:12040:G:A   10:12040
2 chr10:14470:C:T   10:14470
3 chr10:31093:GAC:G 10:31093
4 chr10:36953:G:C   10:36953
5 chr10:37005:C:A   10:37005
6 chr10:40467:A:C   10:40467

In [21]:
dim(ace_snps)

[1] 55254922        2

In [16]:
ace_sub <- ace_snps[ace_snps$V2 %in% hm3_snps$V1,]

In [17]:
table(ace_sub$V2)

 1:100000723  1:100003060  1:100007048  1:100008900  1:100010150  1:100011106
           1            1            1            1            1            1
 1:100011259  1:100016840  1:100016984  1:100017222  1:100018449  1:100020432
           1            1            1            1            1            1
 1:100022621  1:100023572  1:100023708  1:100025136  1:100026912  1:100027311
           1            1            1            1            1            1
 1:100029836  1:100031535  1:100032479  1:100037134  1:100038716  1:100040859
           1            1            1            1            1            1
 1:100045118  1:100049941  1:100054755  1:100057980  1:100062644  1:100067831
           1            1            1            1            1            1
 1:100068404  1:100077082  1:100078406  1:100081035   1:10008117  1:100091705
           1            1            1            1            1            1
 1:100097444  1:100099049  1:100099903  1:100109436  1:100110377   1:10011243
           1            1            1            1            1            1
 1:100113771  1:100118532  1:100119190  1:100127097  1:100132743  1:100133311
           1            1            1            1            1            1
 1:100137757  1:100138150  1:100138335  1:100144083  1:100146015  1:100146375
           1            1            1            1            1            1
 1:100147119  1:100152331  1:100158366  1:100171420  1:100172152  1:100174196
           1            1            1            1            1            1
 1:100178354  1:100178539  1:100178944  1:100179332  1:100185108  1:100190709
           1            1            1            1            1            1
 1:100190938  1:100191383  1:100193022  1:100195270  1:100198355  1:100206504
           1            1            1            1            1            1
 1:100214008  1:100218071  1:100218350  1:100224566  1:100227738  1:100230400
           1            1            1            1            1            1
 1:100237513  1:100243745   1:10024621  1:100247744  1:100253574  1:100262582
           1            1            1            1            1            1
 1:100265707  1:100267299  1:100269222  1:100277522  1:100279242  1:100280400
           1            1            1            1            1            1
 1:100297421  1:100300140  1:100300764  1:100305204  1:100315805  1:100318598
           1            1            1            1            1            1
 1:100322653  1:100323814  1:100327143  1:100327575  1:100327590  1:100328378
           1            1            1            1            1            1
 1:100329651  1:100330564  1:100330740  1:100331917  1:100332480  1:100333488
           1            1            1            1            1            1
 1:100333504  1:100334536  1:100335349  1:100336843  1:100340848   1:10034255
           1            1            1            1            1            1
 1:100342807  1:100346303  1:100352908  1:100353172  1:100353717  1:100357220
           1            1            1            1            1            1
 1:100358822  1:100362504  1:100365547  1:100368910  1:100376437  1:100378201
           1            1            1            1            1            1
 1:100381400  1:100388199  1:100397912  1:100398669  1:100398917  1:100404265
           1            1            1            1            1            1
 1:100408152  1:100410949  1:100414469  1:100422060  1:100437380  1:100441022
           1            1            1            1            1            1
 1:100447407  1:100447550  1:100449103  1:100450627  1:100452568  1:100454232
           1            1            1            1            1            1
 1:100460077  1:100464698  1:100465517   1:10046717  1:100477544    1:1004823
           1            1            1            1            1            1
 1:100483469  1:100484304  1:100489976  1:100490922  1:100504790  1:100518883
           1            1            1            1            1            1
 1:100518929  1:100526093  1:100526278  1:100530518  1:100532079  1:100532124
           1            1            1            1            1            1
 1:100532798  1:100537277  1:100538206  1:100540299  1:100541480  1:100541499
           1            1            1            1            1            1
 1:100544459  1:100544511  1:100544521  1:100546956  1:100547899  1:100551383
           1            1            1            1            1            1
 1:100558867  1:100560361  1:100561968  1:100563131  1:100564212  1:100567476
           1            1            1            1            1            1
 1:100575487  1:100576210  1:100578372  1:100578594  1:100578810  1:100579882
           1            1            1            1            1            1
 1:100580536  1:100582137  1:100582259  1:100586100  1:100589446  1:100596590
           1            1            1            1            1            1
 1:100606010  1:100606112  1:100607369  1:100607660  1:100609349  1:100611655
           1            1            1            1            1            1
 1:100611767  1:100612333  1:100612844  1:100612911  1:100613626  1:100618359
           1            1            1            1            1            1
 1:100618717  1:100618986  1:100619538  1:100620279  1:100620319  1:100623523
           1            1            1            1            1            1
 1:100626428  1:100627399  1:100628583  1:100629053  1:100629106  1:100630500
           1            1            1            1            1            1
 1:100639032  1:100639660  1:100639754  1:100640488  1:100641425  1:100643426
           1            1            1            1            1            1
 1:100643875  1:100644048  1:100645649  1:100645726  1:100646059   1:10065349
           1            1            1            1            1            1
  1:10065707  1:100657722  1:100660593  1:100662693  1:100669180  1:100673223
           1            1            1            1            1            1
 1:100676493  1:100682733  1:100702565  1:100703387  1:100703772  1:100705443
           1            1            1            1            1            1
 1:100705798  1:100710095  1:100715786  1:100716020  1:100719028  1:100721663
           1            1            1            1            1            1
 1:100722636  1:100728649  1:100730103  1:100733152  1:100734330  1:100734423
           1            1            1            1            1            1
 1:100736666  1:100736700  1:100738142  1:100738271  1:100738939  1:100739088
           1            1            1            1            1            1
 1:100739172   1:10074168  1:100744097  1:100750497  1:100750518  1:100757101
           1            1            1            1            1            1
 1:100757251  1:100758590  1:100758690  1:100758905  1:100761231  1:100764256
           1            1            1            1            1            1
 1:100765744  1:100768471  1:100770285  1:100770329  1:100770581  1:100773820
           1            1            1            1            1            1
 1:100775337  1:100777037  1:100782392  1:100787410  1:100789524  1:100794999
           1            1            1            1            1            1
 1:100798792  1:100806523  1:100806846  1:100808015  1:100808534    1:1008088
           1            1            1            1            1            1
 1:100809462  1:100809556  1:100810689  1:100810988  1:100811443  1:100812830
           1            1            1            1            1            1
 1:100814678  1:100817538  1:100818471  1:100819991  1:100827055  1:100827303
           1            1            1            1            1            1
 1:100830511  1:100831721  1:100846106  1:100850378  1:100855520  1:100857310
           1            1            1            1            1            1
 1:100862216  1:100862527  1:100862674  1:100864521  1:100865428  1:100872768
           1            1            1            1            1            1
 1:100872926  1:100874578  1:100875527  1:100880934  1:100882544  1:100884750
           1            1            1            1            1            1
 1:100886105  1:100888923  1:100889993  1:100894659  1:100895622  1:100896815
           1            1            1            1            1            1
 1:100907772  1:100912289  1:100913091    1:1009184  1:100920137  1:100920623
           1            1            1            1            1            1
 1:100921341  1:100930315  1:100931187  1:100941963   1:10095225  1:100954850
           1            1            1            1            1            1
 1:100955851  1:100958875  1:100959005  1:100959992  1:100960304  1:100961404
           1            1            1            1            1            1
 1:100964948  1:100970322  1:100973235  1:100973849  1:100976219  1:100976655
           1            1            1            1            1            1
 1:100976811  1:100978145  1:100980265  1:100980720  1:100984119  1:100992307
           1            1            1            1            1            1
 1:100995747  1:100996676  1:101000498  1:101003002  1:101004661  1:101005350
           1            1            1            1            1            1
 1:101007186  1:101010345  1:101020505  1:101024773  1:101025552  1:101028720
           1            1            1            1            1            1
 1:101029269  1:101033126  1:101035066  1:101038523  1:101040570  1:101048152
           1            1            1            1            1            1
 1:101050142  1:101052132   1:10105243  1:101057196  1:101060857  1:101070222
           1            1            1            1            1            1
 1:101074310  1:101075811  1:101077649  1:101077833  1:101085957  1:101086370
           1            1            1            1            1            1
 1:101099029  1:101106332  1:101107852   1:10111232  1:101118107  1:101121263
           2            1            1            1            1            1
 1:101123526  1:101124779  1:101131673  1:101136355  1:101137894  1:101138560
           1            1            1            1            1            1
 1:101138998  1:101139197  1:101139225  1:101139553  1:101141347  1:101147699
           1            1            1            1            1            1
 1:101148700  1:101153820  1:101154683  1:101154814  1:101155173  1:101155890
           1            1            1            1            1            1
 1:101156338  1:101156418  1:101157404  1:101158515  1:101158912  1:101162453
           1            1            1            1            1            1
 1:101163467    1:1011654  1:101166721  1:101173443  1:101174092  1:101179342
           1            1            1            1            1            1
 1:101181524  1:101190114  1:101191629  1:101197881  1:101199255  1:101204372
           1            1            1            1            1            1
 1:101204429  1:101204680  1:101208442  1:101210288  1:101212176  1:101212975
           1            1            1            1            1            1
 1:101215912  1:101216494  1:101217609  1:101218347  1:101218713  1:101218859
           1            1            1            1            1            1
 1:101218962  1:101224714  1:101232832  1:101235876  1:101237269  1:101238940
           1            1            1            1            1            1
 1:101238976  1:101241570  1:101243196  1:101244007  1:101246227  1:101251132
           1            1            1            1            1            1
 1:101257067  1:101259395  1:101260049  1:101260970  1:101265853  1:101265905
           1            1            1            1            1            1
 1:101267085  1:101267358  1:101267549  1:101267772  1:101267977  1:101270487
           1            1            1            1            1            1
 1:101270800  1:101274850  1:101277398  1:101278912  1:101279077  1:101279265
           1            1            1            1            1            1
 1:101279521  1:101280865  1:101281347  1:101281532  1:101282211  1:101282606
           1            1            1            1            1            1
 1:101284418  1:101284492  1:101285191  1:101287545  1:101291001  1:101292308
           1            1            1            1            1            1
 1:101295333  1:101300338  1:101300369  1:101301718  1:101303312  1:101303877
           1            1            1            1            1            1
 1:101303900  1:101304625  1:101304911  1:101305158  1:101305302  1:101305642
           1            1            1            1            1            1
 1:101305749  1:101306664  1:101306695  1:101307500  1:101308470  1:101309374
           1            1            1            1            1            1
 1:101312680  1:101313916  1:101314118  1:101316172  1:101316568  1:101318784
           1            1            1            1            1            1
 1:101320865  1:101329473   1:10132968    1:1013312  1:101335786  1:101336633
           1            1            1            1            1            1
 1:101343662  1:101350048  1:101353643  1:101354021    1:1013541  1:101363442
           1            1            1            1            1            1
 1:101364368  1:101364635  1:101365069  1:101365302  1:101366282  1:101367921
           1            1            1            1            1            1
 1:101368524  1:101369167  1:101371084  1:101371256  1:101372508  1:101376397
           1            1            1            1            1            1
 1:101376570  1:101376893  1:101377110  1:101377382  1:101377593  1:101377698
           1            1            1            1            1            1
 1:101382289  1:101382781  1:101383163  1:101383838  1:101383867  1:101384274
           1            1            1            1            1            1
 1:101384574  1:101385469  1:101385791  1:101385921  1:101386424  1:101391561
           1            1            1            1            1            1
 1:101392646  1:101393497  1:101393732  1:101396547  1:101398659  1:101399456
           1            1            1            1            1            1
 1:101403357   1:10140516  1:101407309  1:101407514  1:101408860  1:101411090
           1            1            1            1            1            1
 1:101417319  1:101420894  1:101429207  1:101430389  1:101430764  1:101432415
           1            1            1            1            1            1
 1:101437444  1:101440725  1:101440856   1:10144128  1:101441349  1:101442841
           1            1            1            1            1            1
 1:101447606  1:101447971  1:101447982  1:101452820  1:101454246  1:101454406
           1            1            1            1            1            1
 1:101455249  1:101457659  1:101458750  1:101461482  1:101461765  1:101462111
           1            1            1            1            1            1
 1:101462840  1:101464824  1:101466458  1:101469119  1:101471825  1:101471860
           1            1            1            1            1            1
 1:101472158  1:101473005  1:101474133  1:101474918  1:101475253  1:101479615
           1            1            1            1            1            1
 1:101480098  1:101480421  1:101484510  1:101484714  1:101485839  1:101486137
           1            1            1            1            1            1
   1:1014863  1:101486617  1:101488187   1:10149361   1:10149499  1:101495586
           1            1            1            1            1            1
 1:101497326  1:101497396  1:101497658  1:101498210  1:101500389  1:101507429
           1            1            1            1            1            1
 1:101507494  1:101507919  1:101508057  1:101510681  1:101510772  1:101510997
           1            1            1            1            1            1
 1:101512042  1:101518252  1:101519376  1:101520225  1:101525843  1:101526666
           1            1            1            1            1            1
 1:101526916  1:101528464  1:101528651  1:101529785  1:101530541  1:101534513
           1            1            1            1            1            1
 1:101539098  1:101539472  1:101542058  1:101543629  1:101543796  1:101544211
           1            1            1            1            1            1
 1:101544546  1:101546272  1:101546354  1:101546379  1:101547169  1:101547421
           1            1            1            1            1            1
 1:101547912  1:101550538  1:101550892  1:101551156  1:101551544  1:101551882
           1            1            1            1            1            1
 1:101554702  1:101554776  1:101554822  1:101558561  1:101559386  1:101559434
           1            1            1            1            1            1
 1:101567983  1:101570809  1:101574248  1:101574963  1:101574978  1:101576002
           1            1            1            1            1            1
 1:101576874  1:101582696  1:101585464  1:101587401   1:10159144  1:101603910
           1            1            1            1            1            1
 1:101604153  1:101605036  1:101608919  1:101610443  1:101613757  1:101615091
           1            1            1            1            1            1
 1:101616680  1:101619942  1:101620252  1:101622586  1:101622761  1:101623328
           1            1            1            1            1            1
 1:101624618  1:101624710  1:101625108  1:101630356  1:101635667  1:101638570
           1            1            1            1            1            1
 1:101642525  1:101645157  1:101646612  1:101649954  1:101654641  1:101657766
           1            1            1            1            1            1
 1:101664048  1:101676031  1:101689550   1:10169100  1:101695773   1:10170448
           1            1            1            1            1            1
 1:101710863  1:101713980   1:10171405  1:101716267  1:101717068   1:10171927
           1            1            1            1            1            1
 1:101721388   1:10172142  1:101723694  1:101723916  1:101727253  1:101728340
           1            1            1            1            1            1
 1:101728831  1:101731957  1:101732234  1:101733458  1:101733839  1:101734534
           1            1            1            1            1            1
 1:101735274  1:101736149   1:10173698  1:101738258   1:10173977  1:101746149
           1            1            1            1            1            1
 1:101751625  1:101756527  1:101758172   1:10175888   1:10175981  1:101762891
           1            1            1            1            1            1
  1:10176344  1:101763609  1:101764223  1:101764243  1:101767919  1:101768278
           1            1            1            1            1            1
 1:101769408  1:101769937  1:101770123  1:101770566  1:101772262  1:101772580
           1            1            1            1            1            1
 1:101772732  1:101773649  1:101774940  1:101775284  1:101775885  1:101776054
           1            1            1            1            1            1
 1:101777545  1:101781393   1:10178712  1:101787566  1:101787989  1:101789148
           1            1            1            1            1            1
  1:10179139  1:101791907  1:101794716  1:101796088  1:101798353  1:101802255
           1            1            1            1            1            1
 1:101806218  1:101808720  1:101809501  1:101809634  1:101810587  1:101814017
           1            1            1            1            1            1
  1:10181529  1:101817983  1:101819223  1:101819272  1:101819487  1:101819729
           1            1            1            1            1            1

In [20]:
dim(ace_sub)

[1] 1052816       2

In [22]:
head(ace_sub)

    V1              V2
422 chr10:80130:C:T 10:80130
523 chr10:85696:T:C 10:85696
588 chr10:89716:T:G 10:89716
592 chr10:89768:G:A 10:89768
595 chr10:89913:A:G 10:89913
698 chr10:97603:G:A 10:97603

In [19]:
write.csv(ace_sub, "ace_sub_table.csv")

In [24]:
writeLines(as.character(ace_sub$V1), con = "filtered_snps_hm3.txt")