In [1]:
library(tidyverse)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.6     ✔ purrr   0.3.4
✔ tibble  3.1.7     ✔ dplyr   1.0.7
✔ tidyr   1.1.4     ✔ stringr 1.4.0
✔ readr   2.0.2     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [4]:
iid_list <- read_table("/u/project/geschwind/shared/GenomicDatasets-processed/Imputed/total_vcfs_r2_0.8/combined/merged_output_2_iids.txt", col_names = F)

── Column specification ────────────────────────────────────────────────────────
cols(
  X1 = col_character()
)

In [5]:
head(iid_list)

  X1
1 AU003305_AU003305
2 AU0226302_AU0226302
3 AU0226303_AU0226303
4 AU025304_AU025304
5 AU025804_AU025804
6 MN.308_MN.308

In [34]:
dim(iid_list)

[1] 2612    1

In [35]:
2612-1785

[1] 827

In [6]:
colnames(iid_list) <- "original"

In [12]:
iid_list_split <- iid_list %>%
  mutate(original_names = original) %>%
  separate(original, into = c("new_name", "dup"), sep = "_")

In [13]:
head(iid_list_split)

  new_name  dup       original_names
1 AU003305  AU003305  AU003305_AU003305
2 AU0226302 AU0226302 AU0226302_AU0226302
3 AU0226303 AU0226303 AU0226303_AU0226303
4 AU025304  AU025304  AU025304_AU025304
5 AU025804  AU025804  AU025804_AU025804
6 MN.308    MN.308    MN.308_MN.308

In [14]:
mismatch_rows <- iid_list_split[iid_list_split$new_name != iid_list_split$dup, ]

In [15]:
mismatch_rows

  new_name dup original_names
1 NP90     09  NP90_09
2 A292     09  A292_09

In [16]:
renaming_df <- iid_list_split[,c("original_names", "new_name")]

In [17]:
head(renaming_df)

  original_names      new_name
1 AU003305_AU003305   AU003305
2 AU0226302_AU0226302 AU0226302
3 AU0226303_AU0226303 AU0226303
4 AU025304_AU025304   AU025304
5 AU025804_AU025804   AU025804
6 MN.308_MN.308       MN.308

In [19]:
# Specify the file path for the renaming file
renaming_file <- "/u/project/geschwind/shared/GenomicDatasets-processed/Imputed/total_vcfs_r2_0.8/combined/modified_vcf_iids/ace_vcf_rename.txt"

# Write the renaming data frame to a tab-delimited text file
write.table(renaming_df, file = renaming_file, sep = "\t", row.names = FALSE, col.names = FALSE, quote = FALSE)

In [22]:
afr_iids <- read_table("/u/home/a/afcarrol/project-pasaniuc/Projects/20240318_ACE_SPARK_SAIGE_prep/ace_afr_gia.txt", col_names =FALSE)

── Column specification ────────────────────────────────────────────────────────
cols(
  X1 = col_character()
)

In [23]:
head(afr_iids)

  X1
1 702-B-80313.01_702-B-80313.01
2 702-B-80313.02_702-B-80313.02
3 702-B-80313.03_702-B-80313.03
4 702-B-80349.03_702-B-80349.03
5 702-C-80366.01_702-C-80366.01
6 702-C-80366.02_702-C-80366.02

In [27]:
length(unique(afr_iids$X1))

[1] 1785

In [29]:
length(afr_iids$X1 %in% iid_list)

[1] 1785

In [31]:
head(iid_list)

  original
1 AU003305_AU003305
2 AU0226302_AU0226302
3 AU0226303_AU0226303
4 AU025304_AU025304
5 AU025804_AU025804
6 MN.308_MN.308

In [ ]:
AU5305301_AU5305301