In [1]:
library(dplyr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [2]:
getwd()

[1] "/u/project/pasaniuc/afcarrol/Projects/20231003_SPARK_PCA_GIA"

In [3]:
one_kg <- read.table('/u/project/pasaniuc/afcarrol/Projects/20230930_1kg_variants/1kg_var.snplist')

In [4]:
head(one_kg)

  V1
1 1:58814:G:A
2 1:792461:G:A
3 1:817341:A:G
4 1:823656:G:A
5 1:858952:G:A
6 1:894801:A:G

In [5]:
imputed_data <- read.table('/u/project/pasaniuc/afcarrol/Projects/20231003_SPARK_PCA_GIA/combined_variants.txt')

In [10]:
one_kg$id <- paste("chr", one_kg$V1, sep = "")

In [11]:
head(one_kg)

  V1           id
1 1:58814:G:A  chr1:58814:G:A
2 1:792461:G:A chr1:792461:G:A
3 1:817341:A:G chr1:817341:A:G
4 1:823656:G:A chr1:823656:G:A
5 1:858952:G:A chr1:858952:G:A
6 1:894801:A:G chr1:894801:A:G

In [6]:
head(imputed_data)

  V1 V2        V3                 V4 V5
1 1   10000044 chr1:10000044:A:T  A  T
2 1  100000723 chr1:100000723:G:A G  A
3 1  100000839 chr1:100000839:T:A T  A
4 1  100001396 chr1:100001396:G:C G  C
5 1  100001756 chr1:100001756:T:C T  C
6 1  100002235 chr1:100002235:A:G A  G

In [7]:
colnames(imputed_data) <- c("chr", "pos", "id", "ref", "alt")

In [8]:
table(imputed_data$chr)

     1      2      3      4      5      6      7      8      9     10     11
788413 853637 737265 740696 665608 685853 600764 578587 441118 519122 510116
    12     13     14     15     16     17     18     19     20     21     22
498286 374739 332301 273281 300157 249688 282788 206017 214676 128640 124088

In [12]:
final_snps <- imputed_data[imputed_data$id %in% one_kg$id ,]

In [13]:
table(final_snps$chr)

    1     2     3     4     5     6     7     8     9    10    11    12    13
31199 33041 28079 26124 24079 30537 22679 20979 17672 20501 20021 19615 14648
   14    15    16    17    18    19    20    21    22
13127 12050 13103 11254 12066  8652  9796  5454  5668

In [14]:
head(final_snps)

    chr pos       id                 ref alt
2   1   100000723 chr1:100000723:G:A G   A
112 1   100027311 chr1:100027311:A:G A   G
126 1   100029864 chr1:100029864:G:T G   T
219 1   100053276 chr1:100053276:T:C T   C
306 1   100080689 chr1:100080689:A:G A   G
317 1   100082438 chr1:100082438:T:C T   C

In [16]:
table(table(final_snps$id))

     1
400344

In [15]:
writeLines(as.character(final_snps$id), con = "filtered_snps_1kg_spark.txt")

In [18]:
getwd()

[1] "/u/project/pasaniuc/afcarrol/Projects/20231003_SPARK_PCA_GIA"