In [1]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
# Set the directory path containing the files
directory_path <- "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g1/"
# Initialize an empty data frame to store the results
result <- data.frame()

In [3]:
# Loop through files from ace_chr1 to ace_chr22
for (chr in 1:22) {
    

  # Construct the file path
  file_path <- paste0(directory_path, "chr", chr, ".rfmix.Q")
  print(file_path)
  # Read the data from the current file
  data <- read.table(file_path, header = F, sep = "\t")
  colnames(data) <- c("IID", "CEU", "EAS", "PEL", "SAS", "YRI")
  # Combine the results for each ancestry (ANC1 and ANC2)
  result <- rbind(result, data)
}

[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g1/chr1.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g1/chr2.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g1/chr3.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g1/chr4.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g1/chr5.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g1/chr6.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g1/chr7.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g1/chr8.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g1/chr9.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g1/chr10.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g1/chr11.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g1/chr12.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g1/chr13.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g1/chr14.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g1/chr15.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g1/chr16.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g1/chr17.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g1/chr18.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g1/chr19.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g1/chr20.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g1/chr21.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g1/chr22.rfmix.Q"

In [4]:
head(result)

  IID                 CEU     EAS     PEL     SAS     YRI
1 SF0000003_SP0000003 0.21847 0.00000 0.48130 0.00000 0.30023
2 SF0030253_SP0000006 0.90114 0.00736 0.00000 0.08139 0.01011
3 SF0031322_SP0000007 0.99074 0.00000 0.00000 0.00257 0.00669
4 SF0013567_SP0000009 0.97339 0.00000 0.00455 0.02206 0.00000
5 SF0024927_SP0000014 0.90920 0.00000 0.00623 0.03083 0.05374
6 SF0020550_SP0000015 0.94171 0.01155 0.00816 0.03859 0.00000

In [5]:
# Sum the scores across all chromosomes for each individual by ancestry
final_result <- result %>%
  group_by(IID) %>%
  summarize(
    CEU_avg = mean(CEU),
    YRI_avg = mean(YRI),
    EAS_avg = mean(EAS),
    PEL_avg = mean(PEL),
    SAS_avg = mean(SAS)
      
  )

In [6]:
dim(final_result)

[1] 34158     6

In [7]:
fr_g1 <- final_result

In [8]:
write_csv(fr_g1, "spark_g1_hm3_anc_global_prop.csv")

In [9]:
rm(final_result, result, directory_path)

In [10]:
# Set the directory path containing the files
directory_path <- "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g2/"
# Initialize an empty data frame to store the results
result <- data.frame()

In [11]:
# Loop through files from ace_chr1 to ace_chr22
for (chr in 1:22) {
    

  # Construct the file path
  file_path <- paste0(directory_path, "chr", chr, ".rfmix.Q")
  print(file_path)
  # Read the data from the current file
  data <- read.table(file_path, header = F, sep = "\t")
  colnames(data) <- c("IID", "CEU", "EAS", "PEL", "SAS", "YRI")
  # Combine the results for each ancestry (ANC1 and ANC2)
  result <- rbind(result, data)
}

[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g2/chr1.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g2/chr2.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g2/chr3.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g2/chr4.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g2/chr5.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g2/chr6.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g2/chr7.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g2/chr8.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g2/chr9.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g2/chr10.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g2/chr11.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g2/chr12.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g2/chr13.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g2/chr14.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g2/chr15.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g2/chr16.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g2/chr17.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g2/chr18.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g2/chr19.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g2/chr20.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g2/chr21.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240910_spark_global_rfmix/out_g2/chr22.rfmix.Q"

In [12]:
# Sum the scores across all chromosomes for each individual by ancestry
final_result <- result %>%
  group_by(IID) %>%
  summarize(
    CEU_avg = mean(CEU),
    YRI_avg = mean(YRI),
    EAS_avg = mean(EAS),
    PEL_avg = mean(PEL),
    SAS_avg = mean(SAS)
      
  )

In [13]:
dim(final_result)

[1] 34158     6

In [14]:
fr_g2 <- final_result

In [15]:
write_csv(fr_g2, "spark_g2_hm3_anc_global_prop.csv")

In [16]:
total_spark <- rbind(fr_g1, fr_g2)

In [17]:
head(total_spark)

  IID                 CEU_avg   YRI_avg      EAS_avg      PEL_avg
1 SF0000003_SP0000003 0.3353455 0.2633045455 0.0041322727 0.3761400000
2 SF0000017_SP0000017 0.9849441 0.0001986364 0.0027790909 0.0020050000
3 SF0000027_SP0000027 0.9878650 0.0031945455 0.0006777273 0.0002795455
4 SF0000027_SP0000034 0.9912132 0.0012790909 0.0009250000 0.0003231818
5 SF0000027_SP0000051 0.9868232 0.0036009091 0.0003609091 0.0002650000
6 SF0000027_SP0000063 0.9891477 0.0028468182 0.0006154545 0.0000000000
  SAS_avg
1 0.021079545
2 0.010073182
3 0.007982273
4 0.006259545
5 0.008950909
6 0.007390000

In [18]:
length(unique(total_spark$IID))

[1] 68316

In [19]:
write_csv(total_spark, "spark_total_hm3_anc_global_prop.csv")