In [1]:
library(tidyverse)
library(data.table)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.3     ✔ purrr   0.3.4
✔ tibble  3.1.2     ✔ dplyr   1.0.6
✔ tidyr   1.1.3     ✔ stringr 1.4.0
✔ readr   1.4.0     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()


Attaching package: ‘data.table’


The following objects are masked from ‘package:dplyr’:

    between, first, last


The following object is masked from ‘package:purrr’:

    transpose

In [3]:
#qmb <- fread("/u/home/a/aflynnca/project-pasaniuc/projects/20241015_asd_pgs/20241125_run_mod_asd_score/qmb/score/aggregated_scores.txt.gz")

In [4]:
#head(qmb)

  sampleset IID                 DENOM asd_grove_qmb_SUM asd_grove_qmb_AVG
1 SPARK     SF0000003_SP0000003 280   0.3057328         0.001091903
2 SPARK     SF0030253_SP0000006 280   0.4941122         0.001764686
3 SPARK     SF0031322_SP0000007 280   0.4583537         0.001636977
4 SPARK     SF0013567_SP0000009 280   0.4962490         0.001772318
5 SPARK     SF0024927_SP0000014 280   0.3689086         0.001317531
6 SPARK     SF0020550_SP0000015 280   0.3606453         0.001288019

In [4]:
qmb <- fread("/u/home/a/aflynnca/project-pasaniuc/projects/20241015_asd_pgs/20241125_run_mod_asd_score/qmb/score/aggregated_scores.txt.gz")
hmb <- fread("/u/home/a/aflynnca/project-pasaniuc/projects/20241015_asd_pgs/20241125_run_mod_asd_score/hmb/score/aggregated_scores.txt.gz")
mb1 <- fread("/u/home/a/aflynnca/project-pasaniuc/projects/20241015_asd_pgs/20241125_run_mod_asd_score/1mb/score/aggregated_scores.txt.gz")
mb2 <- fread("/u/home/a/aflynnca/project-pasaniuc/projects/20241015_asd_pgs/20241125_run_mod_asd_score/2mb/score/aggregated_scores.txt.gz")
mb5 <- fread("/u/home/a/aflynnca/project-pasaniuc/projects/20241015_asd_pgs/20241125_run_mod_asd_score/5mb/score/aggregated_scores.txt.gz")

In [5]:
mbag <- fread("/u/home/a/aflynnca/project-pasaniuc/projects/20241015_asd_pgs/20241125_run_mod_asd_score/asd_genes/score/aggregated_scores.txt.gz")

In [14]:
head(mbag)

  sampleset IID                 DENOM asd_genes_SUM asd_genes_AVG
1 SPARK     SF0000003_SP0000003 608   0.6659425     0.001095300
2 SPARK     SF0030253_SP0000006 608   1.6211539     0.002666372
3 SPARK     SF0031322_SP0000007 608   1.3327573     0.002192035
4 SPARK     SF0013567_SP0000009 608   2.2390709     0.003682682
5 SPARK     SF0024927_SP0000014 608   1.3766629     0.002264248
6 SPARK     SF0020550_SP0000015 608   2.0502824     0.003372175

In [6]:
#total_scores <- left_join(qmb[,c("IID", "asd_grove_qmb_SUM")], hmb[,c("IID", "asd_grove_hmb_SUM")])
total_scores <- hmb[,c("IID", "asd_grove_hmb_SUM")]

In [5]:
head(total_scores)

  IID                 asd_grove_hmb_SUM
1 SF0000003_SP0000003 0.1039100
2 SF0030253_SP0000006 0.1261550
3 SF0031322_SP0000007 0.1469340
4 SF0013567_SP0000009 0.0921535
5 SF0024927_SP0000014 0.0502924
6 SF0020550_SP0000015 0.1579806

In [7]:
head(mb1)

  sampleset IID                 DENOM asd_grove_1mb_SUM asd_grove_1mb_AVG
1 SPARK     SF0000003_SP0000003 1570  -0.2912263        -1.854945e-04
2 SPARK     SF0030253_SP0000006 1570  -0.9581672        -6.102976e-04
3 SPARK     SF0031322_SP0000007 1570   0.5794369         3.690681e-04
4 SPARK     SF0013567_SP0000009 1570   0.0905321         5.766376e-05
5 SPARK     SF0024927_SP0000014 1570  -1.4983698        -9.543757e-04
6 SPARK     SF0020550_SP0000015 1570  -0.2257843        -1.438117e-04

In [8]:
total_scores <- left_join(total_scores, mb1[,c("IID", "asd_grove_1mb_SUM")])

Joining, by = "IID"

In [9]:
total_scores <- left_join(total_scores, mb2[,c("IID", "asd_grove_2mb_SUM")])

Joining, by = "IID"

In [10]:
total_scores <- left_join(total_scores, mb5[,c("IID", "asd_grove_5mb_SUM")])

Joining, by = "IID"

In [11]:
total_scores <- left_join(total_scores, qmb[,c("IID", "asd_grove_qmb_SUM")])

Joining, by = "IID"

In [15]:
total_scores <- left_join(total_scores, mbag[,c("IID", "asd_genes_SUM")])

Joining, by = "IID"

In [16]:
head(total_scores)

  IID                 asd_grove_hmb_SUM asd_grove_1mb_SUM asd_grove_2mb_SUM
1 SF0000003_SP0000003 -1.0162536        -0.2912263        -0.0911686
2 SF0030253_SP0000006 -0.8173052        -0.9581672        -1.1492374
3 SF0031322_SP0000007 -1.2812106         0.5794369         0.4869355
4 SF0013567_SP0000009 -1.0778119         0.0905321         0.2528806
5 SF0024927_SP0000014 -1.8999342        -1.4983698        -0.0942635
6 SF0020550_SP0000015 -1.0532187        -0.2257843         0.6156997
  asd_grove_5mb_SUM asd_grove_qmb_SUM asd_genes_SUM
1 -4.653513         -0.3070926        0.6659425
2 -4.195624         -0.9080558        1.6211539
3 -3.838729         -0.8248498        1.3327573
4 -4.347138         -0.4993547        2.2390709
5 -4.348595         -1.9259705        1.3766629
6 -2.866284         -0.7921775        2.0502824

In [17]:
write.csv(total_scores,"asd_clinvar_pgs_3.csv")