In [1]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
output <- read.csv("ace_rare_anc_deconv.csv")

In [30]:
head(output)

  variant           zeros ones zero_ids  one_ids   EUR
1 chr1:11847267:C:T 0     1    NA        AU3937301 NA
2 chr1:13342921:T:C 0     0    NA        NA        NA
3 chr1:13342933:G:T 0     0    NA        NA        NA
4 chr1:13420931:C:T 0     1    NA        AU1389305 NA
5 chr1:23971953:C:A 0     0    NA        NA        NA
6 chr1:27997351:C:A 1     0    AU1505303 NA        chr1:27997351:C:A:AU1505303
  AFR
1 chr1:11847267:C:T:AU3937301
2 NA
3 NA
4 chr1:13420931:C:T:AU1389305
5 NA
6 NA

In [27]:
output$EUR <- ifelse(is.na(output$zero_ids), NA, paste(output$variant, output$zero_ids, sep = ":"))

In [29]:
output$AFR <- ifelse(is.na(output$one_ids), NA, paste(output$variant, output$one_ids, sep = ":"))

In [31]:
write.csv(output, "ace_rare_anc_deconv_2.csv")

In [32]:
unique(na.omit(output$EUR))

 [1] "chr1:27997351:C:A:AU1505303"   "chr1:98684921:A:G:AU3128302"
 [3] "chr1:154331447:C:T:AU3197301"  "chr1:160231296:C:T:AU4882301"
 [5] "chr2:233713759:G:A:AU3853302"  "chr3:39144294:C:T:AU4681301"
 [7] "chr3:121533031:T:C:AU065607"   "chr4:154236363:G:A:AU1174302"
 [9] "chr5:33751447:C:G:AU3197303"   "chr6:100651555:C:A:AU3101302"
[11] "chr7:6115511:C:T:AU4491301"    "chr7:43887412:T:G:AU4657301"
[13] "chr7:143724494:T:C:AU1823302"  "chr8:16120584:C:A:AU3997302"
[15] "chr8:103328324:A:G:AU4784303"  "chr9:136984496:T:TG:AU5067303"
[17] "chr11:5581866:T:G:AU4882302"   "chr11:132310149:C:T:AU3615303"
[19] "chr12:12138844:G:A:AU3197303"  "chr12:25110181:T:C:AU4510302"
[21] "chr14:106062286:T:C:AU1092302" "chr14:106062352:G:C:AU1092302"
[23] "chr14:106062353:C:G:AU1092302" "chr14:106770786:G:A:AU1823301"
[25] "chr16:70829817:G:A:AU084104"   "chr18:58919955:C:A:AU4882303"
[27] "chr19:4852245:C:T:AU4885301"   "chr19:17211896:G:T:AU4510301"
[29] "chr20:33019637:A:G:AU4512301"

In [4]:
test_path <- "/u/home/a/afcarrol/project-pasaniuc/Projects/20240423_ace_partial_hm3/rfmix_out/chr1.msp.tsv"

In [6]:
    # Read the first line of the file to extract column names
    col_names <- readLines(test_path, n = 2)[2]
    col_names <- strsplit(col_names, "\t")[[1]]
    col_names[1] <- substring(col_names[1], 2)  # Remove the leading #

In [7]:
test_file <- read.table(test_path, header = FALSE, sep = "\t", col.names = col_names)

In [8]:
head(test_file)

  chm spos    epos    sgpos egpos n.snps AU003305.0 AU003305.1 AU0226302.0
1 1    903175 1515567 2.24  3.21  107    0          0          0
2 1   1515567 1756186 3.21  3.52   30    0          0          0
3 1   1756186 1985148 3.52  3.80   70    0          0          0
4 1   1985148 2274142 3.80  4.51   85    0          0          0
5 1   2274142 2371472 4.51  4.86   45    0          0          0
6 1   2371472 2419657 4.86  5.04   25    0          0          0
  AU0226302.1 ⋯ DG1580.201.0 DG1580.201.1 DG1580.202.0 DG1580.202.1
1 0           ⋯ 1            1            0            0
2 0           ⋯ 1            1            0            0
3 0           ⋯ 1            1            0            0
4 0           ⋯ 1            1            0            0
5 0           ⋯ 1            1            0            0
6 0           ⋯ 1            1            0            0
  DG1580.301.0 DG1580.301.1 DG1228.202.0 DG1228.202.1 DG1228.302.0 DG1228.302.1
1 1            0            1            1            1            0
2 1            0            1            1            1            0
3 1            0            1            1            1            0
4 1            0            1            1            1            0
5 1            0            1            1            1            0
6 1            0            1            1            1            0

In [9]:
test_sub1 <- test_file[test_file$spos %in% c(1756186, 903175), c("AU3937301.0", "AU3937301.1", "AU1389305.0", "AU1389305.1")]

In [14]:
test_sub1 <- test_file[test_file$spos %in% c(1756186, 903175), c("chm", "spos", "epos", "AU1389305.0", "AU1389305.1")]

In [15]:
test_sub1

  chm spos    epos    AU1389305.0 AU1389305.1
1 1    903175 1515567 1           0
3 1   1756186 1985148 1           0

In [22]:
value_to_check <- 13420931
row_index <- test_file[which(test_file$spos <= value_to_check & test_file$epos >= value_to_check),c("AU3937301.0", "AU3937301.1", "AU1389305.0", "AU1389305.1")]
row_index

   AU3937301.0 AU3937301.1 AU1389305.0 AU1389305.1
95 1           1           1           1