In [3]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [4]:
results <- read.csv("ace_rare_anc_deconv_2.csv")

In [5]:
props <- read.csv("../20240423_ace_partial_hm3/ace_hm3_anc_prop.csv")

In [6]:
psam_df <- read.table("/u/project/geschwind/shared/GenomicDatasets-processed/Imputed/total_vcfs_r2_0.8/combined/merged_output_2.psam")

In [7]:
denovo <- read.table("ACE_de_novo_SNVs_Indels_table_Children_included_in_analysis_v2024-03-14.txt")

In [1]:
admix_indv <- read.table("/u/home/a/afcarrol/project-pasaniuc/Projects/20240514_ACE_AD_2/selected_admix.indiv")

In [8]:
head(admix_indv)

  V1
1 702-A-80345.02
2 702-A-80354.04
3 702-B-80312.01
4 702-B-80313.02
5 702-B-80313.03
6 702-B-80349.03

In [2]:
head(psam_df)

ERROR: Error in head(psam_df): object 'psam_df' not found

In [9]:
head(denovo)

  V1                V2        V3      V4              V5              V6
1 variant           sampleID  role    father_sampleID mother_sampleID gene
2 chr1:11847267:C:T AU3937301 Sibling AU3937201       AU3937202       NPPA
3 chr1:13342921:T:C AU1920301 Sibling AU1920201       AU1920202       PRAMEF14
4 chr1:13342933:G:T AU1920301 Sibling AU1920201       AU1920202       PRAMEF14
5 chr1:13420931:C:T AU1389305 Sibling AU1389201       AU1389202       PRAMEF20
6 chr1:23971953:C:A AU4992303 Sibling AU4992201       AU4992202       SRSF10
  V7                     V8                          V9    V10   V11   V12
1 consequence            hgvsc                       isPTV isMIS isSYN isIndel
2 ["missense_variant"]   ENST00000376480.7:c.296G>A  FALSE TRUE  FALSE FALSE
3 ["synonymous_variant"] ENST00000334600.6:c.1032A>G FALSE FALSE TRUE  FALSE
4 ["synonymous_variant"] ENST00000334600.6:c.1020C>A FALSE FALSE TRUE  FALSE
5 ["synonymous_variant"] ENST00000316412.9:c.1101C>T FALSE FALSE TRUE  FALSE
6 ["missense_variant"]   ENST00000492112.2:c.334G>T  FALSE TRUE  FALSE FALSE
  V13                 V14                     V15
1 gnomad_non_neuro_AF gnomad_non_neuro_AF_AFR MPC
2 1.46e-05            0                       0.023648
3 3.22e-05            0.00040783              NA
4 8.19e-05            0.00011366              NA
5 NA                  NA                      NA
6 NA                  NA                      NA
  V16
1 VarKey
2 chr1:11847267:C:T:AU3937301
3 chr1:13342921:T:C:AU1920301
4 chr1:13342933:G:T:AU1920301
5 chr1:13420931:C:T:AU1389305
6 chr1:23971953:C:A:AU4992303

In [10]:
length(unique(denovo[denovo$V2 %in% psam_df$V1, "V2"]))

[1] 167

In [14]:
head(props)

  IID            CEU_avg   YRI_avg
1 702-A-80310.01 0.9415055 0.05849455
2 702-A-80310.02 0.9827005 0.01729955
3 702-A-80310.03 0.9604350 0.03956500
4 702-A-80310.04 0.9670764 0.03292364
5 702-A-80310.05 0.9534959 0.04650409
6 702-A-80330.01 0.9455314 0.05446864

In [10]:
head(results)

  X variant           zeros ones zero_ids  one_ids
1 1 chr1:11847267:C:T 0     1    NA        AU3937301
2 2 chr1:13342921:T:C 0     0    NA        NA
3 3 chr1:13342933:G:T 0     0    NA        NA
4 4 chr1:13420931:C:T 0     1    NA        AU1389305
5 5 chr1:23971953:C:A 0     0    NA        NA
6 6 chr1:27997351:C:A 1     0    AU1505303 NA
  EUR                         AFR
1 NA                          chr1:11847267:C:T:AU3937301
2 NA                          NA
3 NA                          NA
4 NA                          chr1:13420931:C:T:AU1389305
5 NA                          NA
6 chr1:27997351:C:A:AU1505303 NA

In [7]:
table(c(results$zero_ids, results$one_ids))

 AU031403 AU0638301 AU0638302  AU065607  AU084104 AU0871303 AU1001203 AU1083302
        3         2         1         1         1         5         1         1
AU1092302 AU1174302 AU1226303 AU1226304 AU1226305 AU1277303 AU1309301 AU1309302
        3         1         1         2         1         1         1         1
AU1324302 AU1381301 AU1381302 AU1389304 AU1389305 AU1389306 AU1458307 AU1505303
        2         2         1         3         2         3         2         5
AU1612303 AU1823301 AU1823302 AU1983303 AU2429301 AU2711303 AU2711304 AU3064305
        2         1         1         1         2         3         1         1
AU3101302 AU3128302 AU3197301 AU3197303 AU3305301 AU3397302 AU3450301 AU3493302
        1         5         1         2         1         1         3         2
AU3494301 AU3494302 AU3494303 AU3501302 AU3516304 AU3610302 AU3615303 AU3703301
        1         1         1         2         3         1         1         3
AU3725302 AU3729302 AU3729303 AU3730302 AU3763305 AU3764301 AU3764302 AU3853302
        1         1         1         1         2         2         1         2
AU3937301 AU3997302 AU4491301 AU4505302 AU4506301 AU4510301 AU4510302 AU4512301
        3         1         1         1         1         1         1         2
AU4539306 AU4542301 AU4542303 AU4563301 AU4578301 AU4596302 AU4600301 AU4600302
        2         1         1         2         1         2         3         1
AU4602302 AU4654301 AU4654302 AU4657301 AU4681301 AU4681302 AU4690305 AU4690306
        1         4         2         1         1         1         1         1
AU4698301 AU4717302 AU4717304 AU4726301 AU4728301 AU4752302 AU4753304 AU4754303
        1         3         1         1         2         2         2         1
AU4755301 AU4757301 AU4766301 AU4766302 AU4778302 AU4779302 AU4780302 AU4784303
        1         1         1         1         2         4         1         2
AU4792302 AU4793301 AU4794301 AU4810301 AU4830303 AU4861301 AU4863302 AU4863303
        2         1         1         2         2         3         2         2
AU4882301 AU4882302 AU4882303 AU4885301 AU4885302 AU4896302 AU4904302 AU4927301
        1         1         1         2         2         4         1         1
AU4928302 AU4929303 AU4933301 AU4958302 AU4966301 AU4967301 AU4992302 AU5000302
        1         1         1         1         2         2         1         1
AU5002305 AU5029302 AU5033301 AU5047302 AU5050301 AU5050302 AU5061304 AU5067303
        3         1         2         1         1         1         2         1

In [11]:
sum(!is.na(results$EUR))

[1] 29

In [12]:
sum(!is.na(results$AFR))

[1] 181

In [17]:
eur_df <- results[!is.na(results$zero_ids), c("variant", "zeros", "zero_ids", "EUR")]

In [21]:
colnames(eur_df) <- c("variant", "zeros", "IID", "EUR")

In [18]:
dim(eur_df)

[1] 29  4

In [19]:
afr_df <- results[!is.na(results$one_ids), c("variant", "ones", "one_ids", "AFR")]

In [25]:
colnames(afr_df) <- c("variant", "ones", "IID", "AFR")

In [20]:
dim(afr_df)

[1] 181   4

In [22]:
eur_df <- left_join(eur_df, props)

Joining with `by = join_by(IID)`

In [24]:
dim(eur_df)

[1] 29  6

In [23]:
head(eur_df)

  variant            zeros IID       EUR                          CEU_avg
1 chr1:27997351:C:A  1     AU1505303 chr1:27997351:C:A:AU1505303  0.49850091
2 chr1:98684921:A:G  1     AU3128302 chr1:98684921:A:G:AU3128302  0.18623636
3 chr1:154331447:C:T 1     AU3197301 chr1:154331447:C:T:AU3197301 0.70539636
4 chr1:160231296:C:T 1     AU4882301 chr1:160231296:C:T:AU4882301 0.79572545
5 chr2:233713759:G:A 1     AU3853302 chr2:233713759:G:A:AU3853302 0.18071091
6 chr3:39144294:C:T  1     AU4681301 chr3:39144294:C:T:AU4681301  0.07826136
  YRI_avg
1 0.5014991
2 0.8137636
3 0.2946036
4 0.2042745
5 0.8192891
6 0.9217386

In [26]:
afr_df <- left_join(afr_df, props)

Joining with `by = join_by(IID)`

In [27]:
dim(afr_df)

[1] 181   6

In [28]:
mean(afr_df$YRI)

[1] 0.8251026

In [30]:
sd(afr_df$YRI)

[1] 0.1030673

In [29]:
mean(eur_df$YRI)

[1] 0.4397719

In [31]:
sd(eur_df$YRI)

[1] 0.2189942

In [11]:
unique(na.omit(c(results$zero_ids, results$one_ids)))

  [1] "AU1505303" "AU3128302" "AU3197301" "AU4882301" "AU3853302" "AU4681301"
  [7] "AU065607"  "AU1174302" "AU3197303" "AU3101302" "AU4491301" "AU4657301"
 [13] "AU1823302" "AU3997302" "AU4784303" "AU5067303" "AU4882302" "AU3615303"
 [19] "AU4510302" "AU1092302" "AU1823301" "AU084104"  "AU4882303" "AU4885301"
 [25] "AU4510301" "AU4512301" "AU3937301" "AU1389305" "AU1381301" "AU4927301"
 [31] "AU4967301" "AU0871303" "AU031403"  "AU4717302" "AU4726301" "AU4654301"
 [37] "AU4752302" "AU4810301" "AU4933301" "AU1277303" "AU4717304" "AU4779302"
 [43] "AU1458307" "AU1612303" "AU2711303" "AU3493302" "AU1309302" "AU3729302"
 [49] "AU4904302" "AU1389304" "AU4690305" "AU3064305" "AU1381302" "AU4958302"
 [55] "AU4563301" "AU4596302" "AU4542301" "AU3725302" "AU4578301" "AU4505302"
 [61] "AU2429301" "AU4600301" "AU2711304" "AU4539306" "AU1389306" "AU4863303"
 [67] "AU4780302" "AU4766301" "AU4793301" "AU1983303" "AU5002305" "AU4766302"
 [73] "AU3494302" "AU3703301" "AU5061304" "AU4542303" "AU5029302" "AU3763305"
 [79] "AU3764302" "AU4830303" "AU4728301" "AU1226303" "AU4681302" "AU4929303"
 [85] "AU5033301" "AU3397302" "AU4966301" "AU4602302" "AU3764301" "AU3516304"
 [91] "AU1309301" "AU0638301" "AU0638302" "AU3305301" "AU3501302" "AU4896302"
 [97] "AU4506301" "AU4757301" "AU1226305" "AU1226304" "AU3450301" "AU4861301"
[103] "AU1324302" "AU3730302" "AU4753304" "AU4690306" "AU3494301" "AU4778302"
[109] "AU1083302" "AU4885302" "AU4863302" "AU4698301" "AU4654302" "AU1001203"
[115] "AU4792302" "AU3610302" "AU3729303" "AU4754303" "AU3494303" "AU4992302"
[121] "AU5000302" "AU4928302" "AU4755301" "AU4600302" "AU5050302" "AU5050301"
[127] "AU4794301" "AU5047302"

In [13]:
result_indv <- unique(na.omit(c(results$zero_ids, results$one_ids)))

In [16]:
length(result_indv)

[1] 128

In [15]:
length(result_indv[result_indv %in% admix_indv$V1])

[1] 117

In [17]:
afr_indv <- unique(na.omit(c(results$one_ids)))

In [18]:
length(afr_indv)

[1] 108

In [19]:
length(afr_indv[afr_indv %in% admix_indv$V1])

[1] 97

In [20]:
afr_indv[!(afr_indv %in% admix_indv$V1)]

 [1] "AU4654301" "AU1309302" "AU4958302" "AU3725302" "AU4578301" "AU4966301"
 [7] "AU1309301" "AU4506301" "AU4861301" "AU4753304" "AU4654302"