In [2]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
# Set the directory path containing the files
directory_path <- "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/rfmix_out/"
# Initialize an empty data frame to store the results
result <- data.frame()

In [3]:
# Loop through files from ace_chr1 to ace_chr22
for (chr in 1:22) {
    

  # Construct the file path
  file_path <- paste0(directory_path, "chr", chr, ".rfmix.Q")
  print(file_path)
  # Read the data from the current file
  data <- read.table(file_path, header = F, sep = "\t")
  colnames(data) <- c("IID", "CEU", "YRI")
  # Combine the results for each ancestry (ANC1 and ANC2)
  result <- rbind(result, data)
}

[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/rfmix_out/chr1.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/rfmix_out/chr2.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/rfmix_out/chr3.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/rfmix_out/chr4.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/rfmix_out/chr5.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/rfmix_out/chr6.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/rfmix_out/chr7.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/rfmix_out/chr8.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/rfmix_out/chr9.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/rfmix_out/chr10.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/rfmix_out/chr11.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/rfmix_out/chr12.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/rfmix_out/chr13.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/rfmix_out/chr14.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/rfmix_out/chr15.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/rfmix_out/chr16.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/rfmix_out/chr17.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/rfmix_out/chr18.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/rfmix_out/chr19.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/rfmix_out/chr20.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/rfmix_out/chr21.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/rfmix_out/chr22.rfmix.Q"

In [4]:
# Sum the scores across all chromosomes for each individual by ancestry
final_result <- result %>%
  group_by(IID) %>%
  summarize(
    CEU_avg = mean(CEU),
    YRI_avg = mean(YRI)
  )

In [5]:
write_csv(final_result, "spark_hm3_anc_prop.csv")

In [6]:
head(final_result)

  IID                 CEU_avg   YRI_avg
1 SF0000003_SP0000003 0.7336050 0.2663950000
2 SF0000017_SP0000017 0.9998227 0.0001772727
3 SF0000027_SP0000027 0.9966877 0.0033122727
4 SF0000027_SP0000034 0.9988545 0.0011454545
5 SF0000027_SP0000051 0.9959536 0.0040463636
6 SF0000027_SP0000063 0.9971236 0.0028763636

In [4]:
# Set the directory path containing the files
directory_path <- "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/admix_out/"
# Initialize an empty data frame to store the results
result <- data.frame()

In [5]:
# Loop through files from ace_chr1 to ace_chr22
for (chr in 1:22) {
    
#    chr <- 1
  # Construct the file path
  file_path <- paste0(directory_path, "chr", chr, ".sample_pgs.tsv")
  print(file_path)
  # Read the data from the current file
  data <- read.table(file_path, header = TRUE, , sep = "\t")
  
  # Combine the results for each ancestry (ANC1 and ANC2)
  result <- rbind(result, data)
}

[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/admix_out/chr1.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/admix_out/chr2.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/admix_out/chr3.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/admix_out/chr4.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/admix_out/chr5.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/admix_out/chr6.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/admix_out/chr7.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/admix_out/chr8.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/admix_out/chr9.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/admix_out/chr10.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/admix_out/chr11.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/admix_out/chr12.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/admix_out/chr13.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/admix_out/chr14.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/admix_out/chr15.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/admix_out/chr16.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/admix_out/chr17.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/admix_out/chr18.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/admix_out/chr19.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/admix_out/chr20.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/admix_out/chr21.sample_pgs.tsv"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240422_SPARK_rfmix_test/admix_out/chr22.sample_pgs.tsv"

In [6]:
dim(result)

[1] 1502952       3

In [7]:
final_result <- result %>%
  group_by(indiv) %>%
  summarize(
    ANC1_sum = sum(ANC1, na.rm = TRUE),
    ANC2_sum = sum(ANC2, na.rm = TRUE)
  )

In [8]:
head(final_result)

  indiv               ANC1_sum   ANC2_sum
1 SF0000003_SP0000003 -1.1506867 -0.5591369
2 SF0000017_SP0000017 -0.5121809 -0.0198995
3 SF0000027_SP0000027 -0.6803911  0.2311016
4 SF0000027_SP0000034 -0.8013860  0.3552149
5 SF0000027_SP0000051 -0.6530798  0.3565967
6 SF0000027_SP0000063 -0.5799016  0.2148102

In [9]:
dim(final_result)

[1] 68316     3

In [10]:
final_result$total_pgs <- final_result$ANC1_sum+final_result$ANC2_sum

In [11]:
write_csv(final_result, "spark_hm3_anc_pgs.csv")