In [1]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [14]:
# Set the directory path containing the files
directory_path <- "/u/home/a/afcarrol/project-pasaniuc/Projects/20240718_global_rfmix/out/"
# Initialize an empty data frame to store the results
result <- data.frame()

In [15]:
# Loop through files from ace_chr1 to ace_chr22
for (chr in 1:22) {
    

  # Construct the file path
  file_path <- paste0(directory_path, "chr", chr, ".rfmix.Q")
  print(file_path)
  # Read the data from the current file
  data <- read.table(file_path, header = F, sep = "\t")
  colnames(data) <- c("IID", "CEU", "EAS", "PEL", "SAS", "YRI")
  # Combine the results for each ancestry (ANC1 and ANC2)
  result <- rbind(result, data)
}

[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240718_global_rfmix/out/chr1.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240718_global_rfmix/out/chr2.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240718_global_rfmix/out/chr3.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240718_global_rfmix/out/chr4.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240718_global_rfmix/out/chr5.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240718_global_rfmix/out/chr6.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240718_global_rfmix/out/chr7.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240718_global_rfmix/out/chr8.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240718_global_rfmix/out/chr9.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240718_global_rfmix/out/chr10.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240718_global_rfmix/out/chr11.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240718_global_rfmix/out/chr12.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240718_global_rfmix/out/chr13.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240718_global_rfmix/out/chr14.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240718_global_rfmix/out/chr15.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240718_global_rfmix/out/chr16.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240718_global_rfmix/out/chr17.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240718_global_rfmix/out/chr18.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240718_global_rfmix/out/chr19.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240718_global_rfmix/out/chr20.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240718_global_rfmix/out/chr21.rfmix.Q"
[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240718_global_rfmix/out/chr22.rfmix.Q"

In [16]:
dim(result)

[1] 57464     6

In [ ]:
("IID", "CEU", "YRI", "EAS", "PEL", "SAS")

In [17]:
# Sum the scores across all chromosomes for each individual by ancestry
final_result <- result %>%
  group_by(IID) %>%
  summarize(
    CEU_avg = mean(CEU),
    YRI_avg = mean(YRI),
    EAS_avg = mean(EAS),
    PEL_avg = mean(PEL),
    SAS_avg = mean(SAS)
      
  )

In [18]:
head(final_result)

  IID            CEU_avg   YRI_avg    EAS_avg     PEL_avg   SAS_avg
1 702-A-80310.01 0.3383559 0.05728318 0.019191818 0.4720677 0.11310273
2 702-A-80310.02 0.7060377 0.01594091 0.004824545 0.2589791 0.01421682
3 702-A-80310.03 0.5221018 0.03809773 0.010183182 0.3685555 0.06106000
4 702-A-80310.04 0.5279050 0.03121182 0.011035455 0.3613568 0.06849091
5 702-A-80310.05 0.4902436 0.04206182 0.007442273 0.3956800 0.06457273
6 702-A-80330.01 0.3273127 0.05064409 0.009347727 0.5845164 0.02817773

In [8]:
dim(final_result)

[1] 2612    6

In [19]:
write_csv(final_result, "ace_hm3_anc_global_prop.csv")

In [12]:
chr <- 22
  # Construct the file path
  file_path <- paste0(directory_path, "chr", chr, ".rfmix.Q")
  print(file_path)
  # Read the data from the current file
  tdata <- read.table(file_path, header = F, sep = "\t")
  #colnames(tdata) <- c("IID", "CEU", "YRI", "EAS", "PEL", "SAS")
  # Combine the results for each ancestry (ANC1 and ANC2)

[1] "/u/home/a/afcarrol/project-pasaniuc/Projects/20240718_global_rfmix/out/chr22.rfmix.Q"

In [13]:
head(tdata)

  V1        V2      V3      V4 V5      V6
1 AU003305  0.96670 0.00000 0  0.03330 0.00000
2 AU0226302 0.97763 0.00000 0  0.02237 0.00000
3 AU0226303 0.96872 0.00000 0  0.02237 0.00891
4 AU025304  1.00000 0.00000 0  0.00000 0.00000
5 AU025804  0.47208 0.48234 0  0.04558 0.00000
6 MN.308    0.97713 0.00000 0  0.02287 0.00000

In [ ]:
c("IID", "CEU", "YRI", "EAS", "PEL", "SAS")