In [1]:
library(tidyverse)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.3     ✔ purrr   0.3.4
✔ tibble  3.1.2     ✔ dplyr   1.0.6
✔ tidyr   1.1.3     ✔ stringr 1.4.0
✔ readr   1.4.0     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [2]:
ace_sex <- read.csv("total_sex_check.csv")

In [3]:
head(ace_sex)

  X FID       IID       PEDSEX SNPSEX STATUS  F       file
1 2 AU003305  AU003305  0      1      PROBLEM 1.00000 2010-002.clean101007
2 3 AU020305  AU020305  0      1      PROBLEM 0.99390 2010-002.clean101007
3 4 AU020306  AU020306  0      1      PROBLEM 0.99960 2010-002.clean101007
4 5 AU0226302 AU0226302 0      1      PROBLEM 0.99660 2010-002.clean101007
5 6 AU0226303 AU0226303 0      2      PROBLEM 0.08788 2010-002.clean101007
6 7 AU025304  AU025304  0      1      PROBLEM 0.99790 2010-002.clean101007

In [4]:
table(ace_sex$file)

       2010-002.clean101007        2011-158.clean230815
                        986                         190
  2013-111A.ATN.clean170906        2013-438.clean230817
                         25                          95
      2015-9017.clean170906       2016-9174_clean190123
                        665                         341
    2016-9174-3_clean190123 2017-9154_merge_clean190118
                        133                         178
2017-9154-merge_clean181212       2020-9133.clean201112
                        179                          48
      2022-9163.clean230801
                         92

In [5]:
ex_2011_158_230815 <- read.table("/u/project/pasaniuc/afcarrol/Projects/20230906_imputed_data_qc/ex_2011_158_230815.txt")

In [6]:
head(ex_2011_158_230815)

  V1
1 AU1920201_AU1920201
2 AU1920202_AU1920202
3 AU1920302_AU1920302
4 AU1920303_AU1920303
5 AU2911201_AU2911201
6 AU2911202_AU2911202

In [7]:
dim(ex_2011_158_230815)

[1] 98  1

In [11]:
ex_2011_158_230815$V2 <- gsub("_(.*)", "", ex_2011_158_230815$V1)

In [12]:
head(ex_2011_158_230815)

  V1                  V2
1 AU1920201_AU1920201 AU1920201
2 AU1920202_AU1920202 AU1920202
3 AU1920302_AU1920302 AU1920302
4 AU1920303_AU1920303 AU1920303
5 AU2911201_AU2911201 AU2911201
6 AU2911202_AU2911202 AU2911202

In [8]:
table(table(ace_sex$IID))

   1    2    3
2298  305    8

In [17]:
ace_sex <- ace_sex[!(ace_sex$IID %in% ex_2011_158_230815$V2 & ace_sex$file == "2011-158.clean230815"), ]

In [18]:
table(table(ace_sex$IID))

   1    2    3
2396  207    8

In [20]:
clean101007_total <- read.table("/u/project/pasaniuc/afcarrol/Projects/20230906_imputed_data_qc/ex_2010_002_101007.txt")

In [21]:
clean101007_total$V2 <- gsub("_(.*)", "", clean101007_total$V1)

In [22]:
ace_sex <- ace_sex[!(ace_sex$IID %in% clean101007_total$V2 & ace_sex$file == "2010-002.clean101007"), ]

In [23]:
table(table(ace_sex$IID))

   1    2    3
2436  167    8

In [24]:
clean181212 <- read.table("/u/project/pasaniuc/afcarrol/Projects/20230906_imputed_data_qc/ex_2017_9154_181212.txt")

In [25]:
clean181212$V2 <- gsub("_(.*)", "", clean181212$V1)

In [26]:
ace_sex <- ace_sex[!(ace_sex$IID %in% clean181212$V2 & ace_sex$file == "2017-9154-merge_clean181212"), ]

In [27]:
table(table(ace_sex$IID))

   1    2
2602    9

In [28]:
merge_clean190118 <- read.table("//u/project/pasaniuc/afcarrol/Projects/20230906_imputed_data_qc/ex_2017_9154_190118.txt")

In [29]:
merge_clean190118$V2 <- gsub("_(.*)", "", merge_clean190118$V1)

In [30]:
ace_sex <- ace_sex[!(ace_sex$IID %in% merge_clean190118$V2 & ace_sex$file == "2017-9154_merge_clean190118"), ]

In [31]:
table(table(ace_sex$IID))

   1    2
2610    1

In [34]:
ace_table <- table(ace_sex$IID)

In [35]:
head(ace_table)

            09 702-A-80310.01 702-A-80310.02 702-A-80310.03 702-A-80310.04
             2              1              1              1              1
702-A-80310.05
             1

In [37]:
write.csv(ace_sex, "filtered_ace.csv")